//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArquiteturaTesteASA.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ServiceServidor/", ConfigurationName="ServiceReference1.Service1Soap")]
    public interface Service1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorAgendaProduto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncTerminalServidorAgendaProduto(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorLanctoFinanceiro", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncTerminalServidorLanctoFinanceiro(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorNfe", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncTerminalServidorNfe(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorNfeCfop", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncTerminalServidorNfeCfop(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorNfeDanfe", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncTerminalServidorNfeDanfe(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorNfeFinalizadora", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncTerminalServidorNfeFinalizadora(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorNfeItem", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncTerminalServidorNfeItem(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorPonto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncTerminalServidorPonto(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorSangria", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncTerminalServidorSangria(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorSuprimento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncTerminalServidorSuprimento(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorVenda", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncTerminalServidorVenda(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorVendaItem", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncTerminalServidorVendaItem(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorVendaPagamento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncTerminalServidorVendaPagamento(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld(string traz);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalUneg", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalUneg(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalAberturaCaixa", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalAberturaCaixa();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalPromocaoConvenio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalPromocaoConvenio(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalPromocaoUneg", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalPromocaoUneg(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminaEntregaEndereco", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminaEntregaEndereco(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalProdutoFamilia", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalProdutoFamilia(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalProdutoFamiliaGrupo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalProdutoFamiliaGrupo(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalProdutoFamiliaCategoria", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalProdutoFamiliaCategoria(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalProdutoFamiliaCategoriaSub", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalProdutoFamiliaCategoriaSub(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalUsuarioFuncao", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalUsuarioFuncao(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalFuncionario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalFuncionario(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalUsuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalUsuario(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalTributacao", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalTributacao(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalProduto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalProduto(System.DateTime data, int inicio, int fim);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalConvenio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalConvenio(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalProdutoBarra", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalProdutoBarra(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalProdutoTributacao", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalProdutoTributacao(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalProdutoUneg", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalProdutoUneg(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalProdutoEstoqueDia", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalProdutoEstoqueDia(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalProdutoEstoqueLote", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalProdutoEstoqueLote(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalCrmEspecialidade", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalCrmEspecialidade(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalCrm", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalCrm(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalCrmEndereco", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalCrmEndereco(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalProdutoContar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalProdutoContar(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalCliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalCliente(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalClienteEndereco", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalClienteEndereco(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalClienteTelefone", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalClienteTelefone(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalFornecedor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalFornecedor(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalBanco", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalBanco(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalFinanceiroEvento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalFinanceiroEvento(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalFinanceiroPrazo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalFinanceiroPrazo(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalFinalizadoraSub", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalFinalizadoraSub(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalFinanceiroAdministradora", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalFinanceiroAdministradora(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/TestSyncServidorTerminalFinalizadora", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string TestSyncServidorTerminalFinalizadora(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalIbptAx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalIbptAx(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalNegocioParametro", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalNegocioParametro(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalParametroMarkup", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalParametroMarkup(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalParametroComissao", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalParametroComissao(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalAbcFarma", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalAbcFarma(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalAbcFarmaPeriodo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalAbcFarmaPeriodo(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalProdutoPrincAtivo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalProdutoPrincAtivo(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalClienteFiscal", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalClienteFiscal(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalConvenioCliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalConvenioCliente(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalPromocaoTipo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalPromocaoTipo(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalPromocao", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalPromocao(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalPromocaoProduto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalPromocaoProduto(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalParametroDescConv", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalParametroDescConv(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalParametroDescProd", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalParametroDescProd(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalConvenioFinalizadoraSub", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalConvenioFinalizadoraSub(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalParametroDescProdUneg", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalParametroDescProdUneg();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalParametroDescVendUneg", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalParametroDescVendUneg();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalFinalizadoraUn", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalFinalizadoraUn(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalFinalizadoraSubUn", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalFinalizadoraSubUn(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalParametroDescVend", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalParametroDescVend(System.DateTime data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncServidorTerminalParametroLimpezas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncServidorTerminalParametroLimpezas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/ServiceIdentificaTerminal", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ServiceIdentificaTerminal(string SerieHD);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/ServiceInserirTerminal", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool ServiceInserirTerminal(string terminal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/IdentificaEcf", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string IdentificaEcf(string ecfm_id_marca, string ecfm_id_versao, string ecfm_id_modelo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/IdentificaFinalizadoras", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string IdentificaFinalizadoras(string ecf_numero_serie);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/ContaMaquina", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ContaMaquina();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorDataDeimport", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncTerminalServidorDataDeimport();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorCrm", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncTerminalServidorCrm(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorCrmEndereco", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncTerminalServidorCrmEndereco(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorCliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncTerminalServidorCliente(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorClienteEndereco", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncTerminalServidorClienteEndereco(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorClienteTelefone", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncTerminalServidorClienteTelefone(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorClienteAnvisa", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncTerminalServidorClienteAnvisa(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorClienteFiscal", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncTerminalServidorClienteFiscal(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorPacienteAnvisa", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncTerminalServidorPacienteAnvisa(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorCrediario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncTerminalServidorCrediario(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorCrediarioFinalizadora", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncTerminalServidorCrediarioFinalizadora(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorEcf", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncTerminalServidorEcf(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorEcfDd", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncTerminalServidorEcfDd(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorReducaoZ", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncTerminalServidorReducaoZ(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorReducaoZItens", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncTerminalServidorReducaoZItens(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorRecarga", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncTerminalServidorRecarga(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorRecargaFinalizadora", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncTerminalServidorRecargaFinalizadora(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorPrivateLabel", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncTerminalServidorPrivateLabel(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorPrivateLabelFinalizadora", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncTerminalServidorPrivateLabelFinalizadora(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorCheckin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncTerminalServidorCheckin(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorCheckinItem", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncTerminalServidorCheckinItem(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorCheckout", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncTerminalServidorCheckout(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorCheckoutItem", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncTerminalServidorCheckoutItem(string obj);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ServiceServidor/SyncTerminalServidorAberturaCaixa", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SyncTerminalServidorAberturaCaixa(string obj);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : ArquiteturaTesteASA.ServiceReference1.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<ArquiteturaTesteASA.ServiceReference1.Service1Soap>, ArquiteturaTesteASA.ServiceReference1.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SyncTerminalServidorAgendaProduto(string obj) {
            return base.Channel.SyncTerminalServidorAgendaProduto(obj);
        }
        
        public string SyncTerminalServidorLanctoFinanceiro(string obj) {
            return base.Channel.SyncTerminalServidorLanctoFinanceiro(obj);
        }
        
        public string SyncTerminalServidorNfe(string obj) {
            return base.Channel.SyncTerminalServidorNfe(obj);
        }
        
        public string SyncTerminalServidorNfeCfop(string obj) {
            return base.Channel.SyncTerminalServidorNfeCfop(obj);
        }
        
        public string SyncTerminalServidorNfeDanfe(string obj) {
            return base.Channel.SyncTerminalServidorNfeDanfe(obj);
        }
        
        public string SyncTerminalServidorNfeFinalizadora(string obj) {
            return base.Channel.SyncTerminalServidorNfeFinalizadora(obj);
        }
        
        public string SyncTerminalServidorNfeItem(string obj) {
            return base.Channel.SyncTerminalServidorNfeItem(obj);
        }
        
        public string SyncTerminalServidorPonto(string obj) {
            return base.Channel.SyncTerminalServidorPonto(obj);
        }
        
        public string SyncTerminalServidorSangria(string obj) {
            return base.Channel.SyncTerminalServidorSangria(obj);
        }
        
        public string SyncTerminalServidorSuprimento(string obj) {
            return base.Channel.SyncTerminalServidorSuprimento(obj);
        }
        
        public string SyncTerminalServidorVenda(string obj) {
            return base.Channel.SyncTerminalServidorVenda(obj);
        }
        
        public string SyncTerminalServidorVendaItem(string obj) {
            return base.Channel.SyncTerminalServidorVendaItem(obj);
        }
        
        public string SyncTerminalServidorVendaPagamento(string obj) {
            return base.Channel.SyncTerminalServidorVendaPagamento(obj);
        }
        
        public string HelloWorld(string traz) {
            return base.Channel.HelloWorld(traz);
        }
        
        public string SyncServidorTerminalUneg(System.DateTime data) {
            return base.Channel.SyncServidorTerminalUneg(data);
        }
        
        public string SyncServidorTerminalAberturaCaixa() {
            return base.Channel.SyncServidorTerminalAberturaCaixa();
        }
        
        public string SyncServidorTerminalPromocaoConvenio(System.DateTime data) {
            return base.Channel.SyncServidorTerminalPromocaoConvenio(data);
        }
        
        public string SyncServidorTerminalPromocaoUneg(System.DateTime data) {
            return base.Channel.SyncServidorTerminalPromocaoUneg(data);
        }
        
        public string SyncServidorTerminaEntregaEndereco(System.DateTime data) {
            return base.Channel.SyncServidorTerminaEntregaEndereco(data);
        }
        
        public string SyncServidorTerminalProdutoFamilia(System.DateTime data) {
            return base.Channel.SyncServidorTerminalProdutoFamilia(data);
        }
        
        public string SyncServidorTerminalProdutoFamiliaGrupo(System.DateTime data) {
            return base.Channel.SyncServidorTerminalProdutoFamiliaGrupo(data);
        }
        
        public string SyncServidorTerminalProdutoFamiliaCategoria(System.DateTime data) {
            return base.Channel.SyncServidorTerminalProdutoFamiliaCategoria(data);
        }
        
        public string SyncServidorTerminalProdutoFamiliaCategoriaSub(System.DateTime data) {
            return base.Channel.SyncServidorTerminalProdutoFamiliaCategoriaSub(data);
        }
        
        public string SyncServidorTerminalUsuarioFuncao(System.DateTime data) {
            return base.Channel.SyncServidorTerminalUsuarioFuncao(data);
        }
        
        public string SyncServidorTerminalFuncionario(System.DateTime data) {
            return base.Channel.SyncServidorTerminalFuncionario(data);
        }
        
        public string SyncServidorTerminalUsuario(System.DateTime data) {
            return base.Channel.SyncServidorTerminalUsuario(data);
        }
        
        public string SyncServidorTerminalTributacao(System.DateTime data) {
            return base.Channel.SyncServidorTerminalTributacao(data);
        }
        
        public string SyncServidorTerminalProduto(System.DateTime data, int inicio, int fim) {
            return base.Channel.SyncServidorTerminalProduto(data, inicio, fim);
        }
        
        public string SyncServidorTerminalConvenio(System.DateTime data) {
            return base.Channel.SyncServidorTerminalConvenio(data);
        }
        
        public string SyncServidorTerminalProdutoBarra(System.DateTime data) {
            return base.Channel.SyncServidorTerminalProdutoBarra(data);
        }
        
        public string SyncServidorTerminalProdutoTributacao(System.DateTime data) {
            return base.Channel.SyncServidorTerminalProdutoTributacao(data);
        }
        
        public string SyncServidorTerminalProdutoUneg(System.DateTime data) {
            return base.Channel.SyncServidorTerminalProdutoUneg(data);
        }
        
        public string SyncServidorTerminalProdutoEstoqueDia(System.DateTime data) {
            return base.Channel.SyncServidorTerminalProdutoEstoqueDia(data);
        }
        
        public string SyncServidorTerminalProdutoEstoqueLote(System.DateTime data) {
            return base.Channel.SyncServidorTerminalProdutoEstoqueLote(data);
        }
        
        public string SyncServidorTerminalCrmEspecialidade(System.DateTime data) {
            return base.Channel.SyncServidorTerminalCrmEspecialidade(data);
        }
        
        public string SyncServidorTerminalCrm(System.DateTime data) {
            return base.Channel.SyncServidorTerminalCrm(data);
        }
        
        public string SyncServidorTerminalCrmEndereco(System.DateTime data) {
            return base.Channel.SyncServidorTerminalCrmEndereco(data);
        }
        
        public string SyncServidorTerminalProdutoContar(System.DateTime data) {
            return base.Channel.SyncServidorTerminalProdutoContar(data);
        }
        
        public string SyncServidorTerminalCliente(System.DateTime data) {
            return base.Channel.SyncServidorTerminalCliente(data);
        }
        
        public string SyncServidorTerminalClienteEndereco(System.DateTime data) {
            return base.Channel.SyncServidorTerminalClienteEndereco(data);
        }
        
        public string SyncServidorTerminalClienteTelefone(System.DateTime data) {
            return base.Channel.SyncServidorTerminalClienteTelefone(data);
        }
        
        public string SyncServidorTerminalFornecedor(System.DateTime data) {
            return base.Channel.SyncServidorTerminalFornecedor(data);
        }
        
        public string SyncServidorTerminalBanco(System.DateTime data) {
            return base.Channel.SyncServidorTerminalBanco(data);
        }
        
        public string SyncServidorTerminalFinanceiroEvento(System.DateTime data) {
            return base.Channel.SyncServidorTerminalFinanceiroEvento(data);
        }
        
        public string SyncServidorTerminalFinanceiroPrazo(System.DateTime data) {
            return base.Channel.SyncServidorTerminalFinanceiroPrazo(data);
        }
        
        public string SyncServidorTerminalFinalizadoraSub(System.DateTime data) {
            return base.Channel.SyncServidorTerminalFinalizadoraSub(data);
        }
        
        public string SyncServidorTerminalFinanceiroAdministradora(System.DateTime data) {
            return base.Channel.SyncServidorTerminalFinanceiroAdministradora(data);
        }
        
        public string TestSyncServidorTerminalFinalizadora(System.DateTime data) {
            return base.Channel.TestSyncServidorTerminalFinalizadora(data);
        }
        
        public string SyncServidorTerminalIbptAx(System.DateTime data) {
            return base.Channel.SyncServidorTerminalIbptAx(data);
        }
        
        public string SyncServidorTerminalNegocioParametro(System.DateTime data) {
            return base.Channel.SyncServidorTerminalNegocioParametro(data);
        }
        
        public string SyncServidorTerminalParametroMarkup(System.DateTime data) {
            return base.Channel.SyncServidorTerminalParametroMarkup(data);
        }
        
        public string SyncServidorTerminalParametroComissao(System.DateTime data) {
            return base.Channel.SyncServidorTerminalParametroComissao(data);
        }
        
        public string SyncServidorTerminalAbcFarma(System.DateTime data) {
            return base.Channel.SyncServidorTerminalAbcFarma(data);
        }
        
        public string SyncServidorTerminalAbcFarmaPeriodo(System.DateTime data) {
            return base.Channel.SyncServidorTerminalAbcFarmaPeriodo(data);
        }
        
        public string SyncServidorTerminalProdutoPrincAtivo(System.DateTime data) {
            return base.Channel.SyncServidorTerminalProdutoPrincAtivo(data);
        }
        
        public string SyncServidorTerminalClienteFiscal(System.DateTime data) {
            return base.Channel.SyncServidorTerminalClienteFiscal(data);
        }
        
        public string SyncServidorTerminalConvenioCliente(System.DateTime data) {
            return base.Channel.SyncServidorTerminalConvenioCliente(data);
        }
        
        public string SyncServidorTerminalPromocaoTipo(System.DateTime data) {
            return base.Channel.SyncServidorTerminalPromocaoTipo(data);
        }
        
        public string SyncServidorTerminalPromocao(System.DateTime data) {
            return base.Channel.SyncServidorTerminalPromocao(data);
        }
        
        public string SyncServidorTerminalPromocaoProduto(System.DateTime data) {
            return base.Channel.SyncServidorTerminalPromocaoProduto(data);
        }
        
        public string SyncServidorTerminalParametroDescConv(System.DateTime data) {
            return base.Channel.SyncServidorTerminalParametroDescConv(data);
        }
        
        public string SyncServidorTerminalParametroDescProd(System.DateTime data) {
            return base.Channel.SyncServidorTerminalParametroDescProd(data);
        }
        
        public string SyncServidorTerminalConvenioFinalizadoraSub(System.DateTime data) {
            return base.Channel.SyncServidorTerminalConvenioFinalizadoraSub(data);
        }
        
        public string SyncServidorTerminalParametroDescProdUneg() {
            return base.Channel.SyncServidorTerminalParametroDescProdUneg();
        }
        
        public string SyncServidorTerminalParametroDescVendUneg() {
            return base.Channel.SyncServidorTerminalParametroDescVendUneg();
        }
        
        public string SyncServidorTerminalFinalizadoraUn(System.DateTime data) {
            return base.Channel.SyncServidorTerminalFinalizadoraUn(data);
        }
        
        public string SyncServidorTerminalFinalizadoraSubUn(System.DateTime data) {
            return base.Channel.SyncServidorTerminalFinalizadoraSubUn(data);
        }
        
        public string SyncServidorTerminalParametroDescVend(System.DateTime data) {
            return base.Channel.SyncServidorTerminalParametroDescVend(data);
        }
        
        public string SyncServidorTerminalParametroLimpezas() {
            return base.Channel.SyncServidorTerminalParametroLimpezas();
        }
        
        public string ServiceIdentificaTerminal(string SerieHD) {
            return base.Channel.ServiceIdentificaTerminal(SerieHD);
        }
        
        public bool ServiceInserirTerminal(string terminal) {
            return base.Channel.ServiceInserirTerminal(terminal);
        }
        
        public string IdentificaEcf(string ecfm_id_marca, string ecfm_id_versao, string ecfm_id_modelo) {
            return base.Channel.IdentificaEcf(ecfm_id_marca, ecfm_id_versao, ecfm_id_modelo);
        }
        
        public string IdentificaFinalizadoras(string ecf_numero_serie) {
            return base.Channel.IdentificaFinalizadoras(ecf_numero_serie);
        }
        
        public string ContaMaquina() {
            return base.Channel.ContaMaquina();
        }
        
        public string SyncTerminalServidorDataDeimport() {
            return base.Channel.SyncTerminalServidorDataDeimport();
        }
        
        public string SyncTerminalServidorCrm(string obj) {
            return base.Channel.SyncTerminalServidorCrm(obj);
        }
        
        public string SyncTerminalServidorCrmEndereco(string obj) {
            return base.Channel.SyncTerminalServidorCrmEndereco(obj);
        }
        
        public string SyncTerminalServidorCliente(string obj) {
            return base.Channel.SyncTerminalServidorCliente(obj);
        }
        
        public string SyncTerminalServidorClienteEndereco(string obj) {
            return base.Channel.SyncTerminalServidorClienteEndereco(obj);
        }
        
        public string SyncTerminalServidorClienteTelefone(string obj) {
            return base.Channel.SyncTerminalServidorClienteTelefone(obj);
        }
        
        public string SyncTerminalServidorClienteAnvisa(string obj) {
            return base.Channel.SyncTerminalServidorClienteAnvisa(obj);
        }
        
        public string SyncTerminalServidorClienteFiscal(string obj) {
            return base.Channel.SyncTerminalServidorClienteFiscal(obj);
        }
        
        public string SyncTerminalServidorPacienteAnvisa(string obj) {
            return base.Channel.SyncTerminalServidorPacienteAnvisa(obj);
        }
        
        public string SyncTerminalServidorCrediario(string obj) {
            return base.Channel.SyncTerminalServidorCrediario(obj);
        }
        
        public string SyncTerminalServidorCrediarioFinalizadora(string obj) {
            return base.Channel.SyncTerminalServidorCrediarioFinalizadora(obj);
        }
        
        public string SyncTerminalServidorEcf(string obj) {
            return base.Channel.SyncTerminalServidorEcf(obj);
        }
        
        public string SyncTerminalServidorEcfDd(string obj) {
            return base.Channel.SyncTerminalServidorEcfDd(obj);
        }
        
        public string SyncTerminalServidorReducaoZ(string obj) {
            return base.Channel.SyncTerminalServidorReducaoZ(obj);
        }
        
        public string SyncTerminalServidorReducaoZItens(string obj) {
            return base.Channel.SyncTerminalServidorReducaoZItens(obj);
        }
        
        public string SyncTerminalServidorRecarga(string obj) {
            return base.Channel.SyncTerminalServidorRecarga(obj);
        }
        
        public string SyncTerminalServidorRecargaFinalizadora(string obj) {
            return base.Channel.SyncTerminalServidorRecargaFinalizadora(obj);
        }
        
        public string SyncTerminalServidorPrivateLabel(string obj) {
            return base.Channel.SyncTerminalServidorPrivateLabel(obj);
        }
        
        public string SyncTerminalServidorPrivateLabelFinalizadora(string obj) {
            return base.Channel.SyncTerminalServidorPrivateLabelFinalizadora(obj);
        }
        
        public string SyncTerminalServidorCheckin(string obj) {
            return base.Channel.SyncTerminalServidorCheckin(obj);
        }
        
        public string SyncTerminalServidorCheckinItem(string obj) {
            return base.Channel.SyncTerminalServidorCheckinItem(obj);
        }
        
        public string SyncTerminalServidorCheckout(string obj) {
            return base.Channel.SyncTerminalServidorCheckout(obj);
        }
        
        public string SyncTerminalServidorCheckoutItem(string obj) {
            return base.Channel.SyncTerminalServidorCheckoutItem(obj);
        }
        
        public string SyncTerminalServidorAberturaCaixa(string obj) {
            return base.Channel.SyncTerminalServidorAberturaCaixa(obj);
        }
    }
}
