using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Data.Objects.DataClasses;
using System.Data.Objects;
using ArquiteturaASABusiness.BusinessObjects;


namespace ASArquiteruraData.DataContextInterface
{
    public interface IASAEntities
    {
        IObjectSet<tb_abcfarma> tb_abcfarma { get; }
        IObjectSet<tb_abcfarma_periodo> tb_abcfarma_periodo { get; }
        IObjectSet<tb_abertura_caixa> tb_abertura_caixa { get; }
        IObjectSet<tb_agenda_produto> tb_agenda_produto { get; }
        IObjectSet<tb_banco> tb_banco { get; }
        IObjectSet<tb_cadastro_contador> tb_cadastro_contador { get; }
        IObjectSet<tb_cargo> tb_cargo { get; }
        IObjectSet<tb_ceps> tb_ceps { get; }
        IObjectSet<tb_cfop> tb_cfop { get; }
        IObjectSet<tb_checkin> tb_checkin { get; }
        IObjectSet<tb_checkin_item> tb_checkin_item { get; }
        IObjectSet<tb_checkin_item_tmp> tb_checkin_item_tmp { get; }
        IObjectSet<tb_checkin_tmp> tb_checkin_tmp { get; }
        IObjectSet<tb_checkout> tb_checkout { get; }
        IObjectSet<tb_checkout_item> tb_checkout_item { get; }
        IObjectSet<tb_cliente> tb_cliente { get; }
        IObjectSet<tb_cliente_anvisa> tb_cliente_anvisa { get; }
        IObjectSet<tb_cliente_bloqueio> tb_cliente_bloqueio { get; }
        IObjectSet<tb_cliente_endereco> tb_cliente_endereco { get; }
        IObjectSet<tb_cliente_fiscal> tb_cliente_fiscal { get; }
        IObjectSet<tb_cliente_telefone> tb_cliente_telefone { get; }
        IObjectSet<tb_conselho> tb_conselho { get; }
        IObjectSet<tb_conselho_regional> tb_conselho_regional { get; }
        IObjectSet<tb_conta> tb_conta { get; }
        IObjectSet<tb_convenio> tb_convenio { get; }
        IObjectSet<tb_crediario> tb_crediario { get; }
        IObjectSet<tb_crediario_finalizadora> tb_crediario_finalizadora { get; }
        IObjectSet<tb_crm> tb_crm { get; }
        IObjectSet<tb_crm_endereco> tb_crm_endereco { get; }
        IObjectSet<tb_crm_especialidade> tb_crm_especialidade { get; }
        IObjectSet<tb_dav> tb_dav { get; }
        IObjectSet<tb_dav_itens____> tb_dav_itens____ { get; }
        IObjectSet<tb_ecf> tb_ecf { get; }
        IObjectSet<tb_ecf_dd> tb_ecf_dd { get; }
        IObjectSet<tb_ecf_modelo> tb_ecf_modelo { get; }
        IObjectSet<tb_empresa_privatelabel> tb_empresa_privatelabel { get; }
        IObjectSet<tb_empresa_recarga> tb_empresa_recarga { get; }
        IObjectSet<tb_entrega_arearisco> tb_entrega_arearisco { get; }
        IObjectSet<tb_entrega_endereco> tb_entrega_endereco { get; }
        IObjectSet<tb_entrega_polo> tb_entrega_polo { get; }
        IObjectSet<tb_entrega_polo_bairro> tb_entrega_polo_bairro { get; }
        IObjectSet<tb_entrega_prod_continuo> tb_entrega_prod_continuo { get; }
        IObjectSet<tb_entrega_quadrante> tb_entrega_quadrante { get; }
        IObjectSet<tb_entrega_rota> tb_entrega_rota { get; }
        IObjectSet<tb_entrega_rota_cep> tb_entrega_rota_cep { get; }
        IObjectSet<tb_finalizadora> tb_finalizadora { get; }
        IObjectSet<tb_finalizadora_sub> tb_finalizadora_sub { get; }
        IObjectSet<tb_financeiro_administradora> tb_financeiro_administradora { get; }
        IObjectSet<tb_financeiro_bancos> tb_financeiro_bancos { get; }
        IObjectSet<tb_financeiro_evento> tb_financeiro_evento { get; }
        IObjectSet<tb_financeiro_prazo> tb_financeiro_prazo { get; }
        IObjectSet<tb_financeiro_sangria> tb_financeiro_sangria { get; }
        IObjectSet<tb_financeiro_suprimento> tb_financeiro_suprimento { get; }
        IObjectSet<tb_fornecedor> tb_fornecedor { get; }
        IObjectSet<tb_fornecedor_divisao> tb_fornecedor_divisao { get; }
        IObjectSet<tb_funcionario> tb_funcionario { get; }
        IObjectSet<tb_funcionario_horario> tb_funcionario_horario { get; }
        IObjectSet<tb_funcionario_horario_item> tb_funcionario_horario_item { get; }
        IObjectSet<tb_funcionario_visitante> tb_funcionario_visitante { get; }
        IObjectSet<tb_hist_sangria____> tb_hist_sangria____ { get; }
        IObjectSet<tb_ibge> tb_ibge { get; }
        IObjectSet<tb_ibpt_ax> tb_ibpt_ax { get; }
        IObjectSet<tb_lancto_financeiro> tb_lancto_financeiro { get; }
        IObjectSet<tb_liquidacao_forma> tb_liquidacao_forma { get; }
        IObjectSet<tb_liquidacao_motivo> tb_liquidacao_motivo { get; }
        IObjectSet<tb_mvto_compra____> tb_mvto_compra____ { get; }
        IObjectSet<tb_mvto_compra_dup____> tb_mvto_compra_dup____ { get; }
        IObjectSet<tb_mvto_compra_item____> tb_mvto_compra_item____ { get; }
        IObjectSet<tb_mvto_compra_item_divergencia____> tb_mvto_compra_item_divergencia____ { get; }
        IObjectSet<tb_mvto_compra_item_lote____> tb_mvto_compra_item_lote____ { get; }
        IObjectSet<tb_mvto_fin____> tb_mvto_fin____ { get; }
        IObjectSet<tb_nfe> tb_nfe { get; }
        IObjectSet<tb_nfe_cfop> tb_nfe_cfop { get; }
        IObjectSet<tb_nfe_danfe> tb_nfe_danfe { get; }
        IObjectSet<tb_nfe_finalizadora> tb_nfe_finalizadora { get; }
        IObjectSet<tb_nfe_item> tb_nfe_item { get; }
        IObjectSet<tb_paciente_anvisa> tb_paciente_anvisa { get; }
        IObjectSet<tb_paf_numero> tb_paf_numero { get; }
        IObjectSet<tb_parametro> tb_parametro { get; }
        IObjectSet<tb_parametro_comissao> tb_parametro_comissao { get; }
        IObjectSet<tb_parametro_descconv> tb_parametro_descconv { get; }
        IObjectSet<tb_parametro_descmax> tb_parametro_descmax { get; }
        IObjectSet<tb_parametro_descprod> tb_parametro_descprod { get; }
        IObjectSet<tb_parametro_descvend> tb_parametro_descvend { get; }
        IObjectSet<tb_parametro_limpezas> tb_parametro_limpezas { get; }
        IObjectSet<tb_parametro_markup> tb_parametro_markup { get; }
        IObjectSet<tb_pbm> tb_pbm { get; }
        IObjectSet<tb_pedido_compra____> tb_pedido_compra____ { get; }
        IObjectSet<tb_pedido_compra_item____> tb_pedido_compra_item____ { get; }
        IObjectSet<tb_piscofins> tb_piscofins { get; }
        IObjectSet<tb_ponto> tb_ponto { get; }
        IObjectSet<tb_ponto_motivo> tb_ponto_motivo { get; }
        IObjectSet<tb_princ_ativo> tb_princ_ativo { get; }
        IObjectSet<tb_privatelabel> tb_privatelabel { get; }
        IObjectSet<tb_privatelabel_finalizadora> tb_privatelabel_finalizadora { get; }
        IObjectSet<tb_produto> tb_produto { get; }
        IObjectSet<tb_produto_barra> tb_produto_barra { get; }
        IObjectSet<tb_produto_classe> tb_produto_classe { get; }
        IObjectSet<tb_produto_fam_categ_sub> tb_produto_fam_categ_sub { get; }
        IObjectSet<tb_produto_fam_categoria> tb_produto_fam_categoria { get; }
        IObjectSet<tb_produto_fam_grupo> tb_produto_fam_grupo { get; }
        IObjectSet<tb_produto_familia> tb_produto_familia { get; }
        IObjectSet<tb_produto_kit> tb_produto_kit { get; }
        IObjectSet<tb_produto_linha> tb_produto_linha { get; }
        IObjectSet<tb_produto_piscofins> tb_produto_piscofins { get; }
        IObjectSet<tb_produto_princativo> tb_produto_princativo { get; }
        IObjectSet<tb_produto_receituario> tb_produto_receituario { get; }
        IObjectSet<tb_produto_similaridade> tb_produto_similaridade { get; }
        IObjectSet<tb_promocao> tb_promocao { get; }
        IObjectSet<tb_promocao_tipo> tb_promocao_tipo { get; }
        IObjectSet<tb_recarga> tb_recarga { get; }
        IObjectSet<tb_recarga_finalizadora> tb_recarga_finalizadora { get; }
        IObjectSet<tb_reducao_z> tb_reducao_z { get; }
        IObjectSet<tb_reducao_z_itens> tb_reducao_z_itens { get; }
        IObjectSet<tb_sangrias> tb_sangrias { get; }
        IObjectSet<tb_serie_nota> tb_serie_nota { get; }
        IObjectSet<tb_sincronizacao> tb_sincronizacao { get; }
        IObjectSet<tb_suprimentos> tb_suprimentos { get; }
        IObjectSet<tb_terminal> tb_terminal { get; }
        IObjectSet<tb_terminal_mobile> tb_terminal_mobile { get; }
        IObjectSet<tb_tipo_logradouro> tb_tipo_logradouro { get; }
        IObjectSet<tb_tipo_mvto_produto> tb_tipo_mvto_produto { get; }
        IObjectSet<tb_tipo_nota> tb_tipo_nota { get; }
        IObjectSet<tb_transportadora> tb_transportadora { get; }
        IObjectSet<tb_tributacao> tb_tributacao { get; }
        IObjectSet<tb_uf> tb_uf { get; }
        IObjectSet<tb_unid_negocio> tb_unid_negocio { get; }
        IObjectSet<tb_unid_negocio_grupo> tb_unid_negocio_grupo { get; }
        IObjectSet<tb_unid_negocio_parametro> tb_unid_negocio_parametro { get; }
        IObjectSet<tb_usuario> tb_usuario { get; }
        IObjectSet<tb_usuario_bloqueio> tb_usuario_bloqueio { get; }
        IObjectSet<tb_usuario_dpto> tb_usuario_dpto { get; }
        IObjectSet<tb_usuario_funcao> tb_usuario_funcao { get; }
        IObjectSet<tb_usuario_grupo> tb_usuario_grupo { get; }
        IObjectSet<tb_venda> tb_venda { get; }
        IObjectSet<tb_venda_dav> tb_venda_dav { get; }
        IObjectSet<tb_venda_dav_item> tb_venda_dav_item { get; }
        IObjectSet<tb_venda_estorno_tef> tb_venda_estorno_tef { get; }
        IObjectSet<tb_venda_item> tb_venda_item { get; }
        IObjectSet<tb_venda_pagamento> tb_venda_pagamento { get; }
        IObjectSet<tb_venda_prevenda> tb_venda_prevenda { get; }
        IObjectSet<tb_venda_prevenda_item> tb_venda_prevenda_item { get; }
        IObjectSet<tb_venda_prevenda_pgto> tb_venda_prevenda_pgto { get; }
        IObjectSet<tbManagerUpdate> tbManagerUpdates { get; }
        IObjectSet<tbr_abcfarma_uf> tbr_abcfarma_uf { get; }
        IObjectSet<tbr_convenio_cliente> tbr_convenio_cliente { get; }
        IObjectSet<tbr_convenio_finalizadora_sub> tbr_convenio_finalizadora_sub { get; }
        IObjectSet<tbr_convenio_un> tbr_convenio_un { get; }
        IObjectSet<tbr_dicionario_produto> tbr_dicionario_produto { get; }
        IObjectSet<tbr_dicionario_un> tbr_dicionario_un { get; }
        IObjectSet<tbr_dpto_aplicativo> tbr_dpto_aplicativo { get; }
        IObjectSet<tbr_ecf_finalizadora> tbr_ecf_finalizadora { get; }
        IObjectSet<tbr_ecf_tributacao> tbr_ecf_tributacao { get; }
        IObjectSet<tbr_finalizadora_sub_un> tbr_finalizadora_sub_un { get; }
        IObjectSet<tbr_finalizadora_un> tbr_finalizadora_un { get; }
        IObjectSet<tbr_mvto_compra_cfop____> tbr_mvto_compra_cfop____ { get; }
        IObjectSet<tbr_mvto_compra_dup____> tbr_mvto_compra_dup____ { get; }
        IObjectSet<tbr_parametro_descprod_uneg> tbr_parametro_descprod_uneg { get; }
        IObjectSet<tbr_parametro_descvend_uneg> tbr_parametro_descvend_uneg { get; }
        IObjectSet<tbr_parametro_markup_uneg> tbr_parametro_markup_uneg { get; }
        IObjectSet<tbr_produto_estoque_dia> tbr_produto_estoque_dia { get; }
        IObjectSet<tbr_produto_estoque_lote> tbr_produto_estoque_lote { get; }
        IObjectSet<tbr_produto_tributacao> tbr_produto_tributacao { get; }
        IObjectSet<tbr_produto_uneg> tbr_produto_uneg { get; }
        IObjectSet<tbr_promocao_produto> tbr_promocao_produto { get; }
    }
}
