
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tb_abcfarma_periodo
{

    public tb_abcfarma_periodo()
    {

        this.tbr_abcfarma_uf = new HashSet<tbr_abcfarma_uf>();

    }


    public int per_id { get; set; }

    public string per_periodo { get; set; }

    public Nullable<System.DateTime> per_dt_alteracao { get; set; }

    public Nullable<decimal> per_cpf_alteracao { get; set; }



    public virtual ICollection<tbr_abcfarma_uf> tbr_abcfarma_uf { get; set; }

}

}
