
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tb_agenda_produto
{

    public int uneg_id { get; set; }

    public int agen_pdv { get; set; }

    public int agen_id { get; set; }

    public System.DateTime agen_dt_agenda { get; set; }

    public Nullable<int> pro_id { get; set; }

    public Nullable<System.DateTime> agen_dt_vencimento { get; set; }

    public Nullable<System.DateTime> agen_dt_start { get; set; }

    public Nullable<System.DateTime> agen_dt_venda { get; set; }

    public string agen_status { get; set; }

    public Nullable<System.DateTime> agen_status_data { get; set; }

    public string agen_status_obs { get; set; }

    public Nullable<System.DateTime> agen_dt_alteracao { get; set; }

    public Nullable<int> agen_qtde_embalagem { get; set; }

    public Nullable<int> agen_atde_compra { get; set; }

    public Nullable<int> agen_tmp_consumo_hora { get; set; }

    public Nullable<int> agen_tmp_consumo_diario { get; set; }

    public Nullable<int> agen_tmp_consumo_dia { get; set; }

    public Nullable<int> agen_tmp_consumo_mes { get; set; }

    public Nullable<int> agen_qtde_consumo { get; set; }

    public string agen_nome_contato { get; set; }

    public Nullable<long> agen_tel_residencial { get; set; }

    public Nullable<long> agen_tel_comercial { get; set; }

    public Nullable<long> agen_tel_celular { get; set; }

    public string agen_observacao { get; set; }

    public Nullable<int> agen_agendador { get; set; }

    public Nullable<int> agen_vendedor { get; set; }

    public Nullable<decimal> agen_preco_custo { get; set; }

    public Nullable<decimal> agen_preco_venda { get; set; }

    public Nullable<long> end_telefone { get; set; }



    public virtual tb_produto tb_produto { get; set; }

    public virtual tb_unid_negocio tb_unid_negocio { get; set; }

    public virtual tb_usuario tb_usuario { get; set; }

    public virtual tb_usuario tb_usuario1 { get; set; }

}

}
