
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tb_cadastro_contador
{

    public tb_cadastro_contador()
    {

        this.tb_unid_negocio = new HashSet<tb_unid_negocio>();

    }


    public int cadcont_id { get; set; }

    public string cadcont_nome { get; set; }

    public string cadcont_cpf { get; set; }

    public string cadcont_crc { get; set; }

    public string cadcont_email { get; set; }

    public string cadcont_status { get; set; }

    public Nullable<System.DateTime> cadcont_data_modificacao { get; set; }

    public string cadcont_escritorio_cnpj { get; set; }

    public string cadcont_escritorio_inscricao_estadual { get; set; }

    public string cadcont_escritorio_inscricao_municipal { get; set; }

    public string cadcont_escritorio_razao_social { get; set; }

    public string cadcont_escritorio_nome_fantasia { get; set; }

    public string cadcont_escritorio_endereco { get; set; }

    public string cadcont_escritorio_numero { get; set; }

    public string cadcont_escritorio_complemento { get; set; }

    public string cadcont_escritorio_bairro { get; set; }

    public string cadcont_escritorio_cep { get; set; }

    public Nullable<int> cadcont_escritorio_ddd { get; set; }

    public string cadcont_escritorio_telefone { get; set; }

    public Nullable<int> cadcont_escritorio_ddd_fax { get; set; }

    public string cadcont_escritorio_fax { get; set; }

    public string cadcont_escritorio_email { get; set; }

    public Nullable<int> ibge_codigo { get; set; }



    public virtual tb_ibge tb_ibge { get; set; }

    public virtual ICollection<tb_unid_negocio> tb_unid_negocio { get; set; }

}

}
