
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tb_crm_endereco
{

    public int crm_end_id { get; set; }

    public int crm_id { get; set; }

    public int uf_id { get; set; }

    public string crm_tipo { get; set; }

    public string crm_end_tel { get; set; }

    public string crm_end_cep { get; set; }

    public string crm_end_tp_logradouro { get; set; }

    public string crm_end_nm_logradouro { get; set; }

    public Nullable<int> crm_end_numero { get; set; }

    public string crm_end_complemento { get; set; }

    public string crm_end_bairro { get; set; }

    public string crm_end_referencia { get; set; }

    public string crm_end_cidade { get; set; }

    public string crm_end_situacao { get; set; }

    public Nullable<System.DateTime> crm_end_dt_cadastro { get; set; }

    public Nullable<System.DateTime> crm_end_dt_alteracao { get; set; }

    public string crm_end_cpf_alteracao { get; set; }



    public virtual tb_crm tb_crm { get; set; }

    public virtual tb_uf tb_uf { get; set; }

}

}
