
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tb_cliente
{

    public tb_cliente()
    {

        this.tb_cliente_endereco = new HashSet<tb_cliente_endereco>();

        this.tb_convenio = new HashSet<tb_convenio>();

        this.tb_crediario = new HashSet<tb_crediario>();

        this.tb_funcionario = new HashSet<tb_funcionario>();

        this.tb_venda_dav = new HashSet<tb_venda_dav>();

        this.tb_venda_pagamento = new HashSet<tb_venda_pagamento>();

        this.tb_venda_prevenda = new HashSet<tb_venda_prevenda>();

        this.tb_venda = new HashSet<tb_venda>();

        this.tbr_convenio_cliente = new HashSet<tbr_convenio_cliente>();

    }


    public long cli_id { get; set; }

    public string cli_email { get; set; }

    public Nullable<decimal> cli_limite_compra { get; set; }

    public Nullable<decimal> cli_compra_acumulada { get; set; }

    public Nullable<System.DateTime> cli_dt_bloqueio { get; set; }

    public Nullable<decimal> cli_qtd_bloqueio { get; set; }

    public string cli_obs { get; set; }

    public Nullable<System.DateTime> cli_dt_ultima_compra { get; set; }

    public string cli_cpf_alteracao { get; set; }

    public string cli_tip_pessoa { get; set; }

    public Nullable<int> cli_titular_id { get; set; }

    public string cli_cpf { get; set; }

    public string cli_nome { get; set; }

    public string cli_id_numero { get; set; }

    public string cli_id_orgao_expedidor { get; set; }

    public Nullable<System.DateTime> cli_id_dt_expedicao { get; set; }

    public Nullable<System.DateTime> cli_dt_nascimento { get; set; }

    public string cli_sexo { get; set; }

    public string cli_estado_civil { get; set; }

    public Nullable<decimal> cli_nu_filhos { get; set; }

    public string cli_nm_pai { get; set; }

    public string cli_nm_mae { get; set; }

    public string cli_cnpj { get; set; }

    public Nullable<decimal> cli_insc_estadual { get; set; }

    public string cli_razao_social { get; set; }

    public string cli_nome_fantasia { get; set; }

    public string cli_cnpj_rede { get; set; }

    public Nullable<decimal> cli_vlr_credito { get; set; }

    public Nullable<decimal> cli_polo_distribuidor { get; set; }

    public Nullable<decimal> cli_perc_csub { get; set; }

    public Nullable<decimal> cli_perc_ssub { get; set; }

    public Nullable<bool> cli_venda_imp_fracionada { get; set; }

    public Nullable<bool> cli_venda_imp_princativo { get; set; }

    public string cli_nm_contato { get; set; }

    public string cli_situacao { get; set; }

    public Nullable<System.DateTime> cli_dt_cadastro { get; set; }

    public Nullable<System.DateTime> cli_dt_alteracao { get; set; }

    public Nullable<int> prm_id { get; set; }

    public Nullable<int> final_id { get; set; }

    public Nullable<int> subfin_id { get; set; }

    public Nullable<int> bloq_id { get; set; }

    public Nullable<int> uneg_id { get; set; }

    public Nullable<int> uf_id { get; set; }



    public virtual ICollection<tb_cliente_endereco> tb_cliente_endereco { get; set; }

    public virtual tb_cliente_bloqueio tb_cliente_bloqueio { get; set; }

    public virtual tb_promocao tb_promocao { get; set; }

    public virtual tb_uf tb_uf { get; set; }

    public virtual tb_unid_negocio tb_unid_negocio { get; set; }

    public virtual ICollection<tb_convenio> tb_convenio { get; set; }

    public virtual ICollection<tb_crediario> tb_crediario { get; set; }

    public virtual ICollection<tb_funcionario> tb_funcionario { get; set; }

    public virtual ICollection<tb_venda_dav> tb_venda_dav { get; set; }

    public virtual ICollection<tb_venda_pagamento> tb_venda_pagamento { get; set; }

    public virtual ICollection<tb_venda_prevenda> tb_venda_prevenda { get; set; }

    public virtual ICollection<tb_venda> tb_venda { get; set; }

    public virtual ICollection<tbr_convenio_cliente> tbr_convenio_cliente { get; set; }

}

}
