
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tb_conselho
{

    public tb_conselho()
    {

        this.tb_conselho_regional = new HashSet<tb_conselho_regional>();

    }


    public short cs_id { get; set; }

    public string cs_descricao { get; set; }



    public virtual ICollection<tb_conselho_regional> tb_conselho_regional { get; set; }

}

}
