
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tb_cargo
{

    public tb_cargo()
    {

        this.tb_funcionario = new HashSet<tb_funcionario>();

    }


    public int cargo_id { get; set; }

    public string cargo_descricao { get; set; }

    public string cargo_situacao { get; set; }

    public Nullable<System.DateTime> cargo_dt_cadastro { get; set; }

    public Nullable<System.DateTime> cargo_dt_alteracao { get; set; }



    public virtual ICollection<tb_funcionario> tb_funcionario { get; set; }

}

}
