
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tb_crediario_finalizadora
{

    public int cred_id { get; set; }

    public int uneg_id { get; set; }

    public int venda_pdv { get; set; }

    public int crpgto_id { get; set; }

    public System.DateTime crpgto_data { get; set; }

    public Nullable<decimal> crpgto_valor { get; set; }

    public Nullable<int> crpgto_atendente { get; set; }

    public Nullable<int> crpgto_operadorCX { get; set; }

    public Nullable<int> final_id { get; set; }

    public Nullable<int> subfin_id { get; set; }

    public Nullable<decimal> crpgto_troco { get; set; }

    public Nullable<System.DateTime> crpgto_cli_data_ch { get; set; }

    public Nullable<int> crpgto_cli_banco_id_ch { get; set; }

    public Nullable<decimal> crpgto_cli_agencia_ch { get; set; }

    public Nullable<decimal> crpgto_cli_c1_ch { get; set; }

    public Nullable<decimal> crpgto_cli_conta_corrente_ch { get; set; }

    public Nullable<decimal> crpgto_cli_c2_ch { get; set; }

    public Nullable<decimal> crpgto_cli_numero_ch { get; set; }

    public Nullable<decimal> crpgto_cli_c3_ch { get; set; }

    public Nullable<int> prazo_id { get; set; }

    public Nullable<int> cheqrec_id { get; set; }

    public Nullable<int> bcaixa_id { get; set; }

}

}
