
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tb_checkin_item
{

    public int uneg_id { get; set; }

    public int chkin_pdv { get; set; }

    public int chkin_id { get; set; }

    public System.DateTime chkin_data { get; set; }

    public int ickin_id { get; set; }

    public Nullable<int> pro_id { get; set; }

    public Nullable<decimal> ickin_cd_barra_lido { get; set; }

    public Nullable<decimal> ickin_quantidade { get; set; }

    public string ickin_nu_lote { get; set; }

    public Nullable<System.DateTime> ickin_val_lote { get; set; }

    public Nullable<bool> ickin_conciliacao_nf { get; set; }

}

}
