
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tb_cliente_telefone
{

    public long cli_id { get; set; }

    public int tel_id { get; set; }

    public Nullable<decimal> tel_tipo { get; set; }

    public Nullable<decimal> tel_cod_area { get; set; }

    public Nullable<decimal> tel_numero { get; set; }

    public string tel_situacao { get; set; }

    public Nullable<System.DateTime> tel_dt_cadastro { get; set; }

    public Nullable<System.DateTime> tel_dt_alteracao { get; set; }

    public string tel_cpf_alteracao { get; set; }

}

}
