
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tb_crm_especialidade
{

    public int esp_id { get; set; }

    public string esp_descricao { get; set; }

    public string esp_situacao { get; set; }

    public Nullable<System.DateTime> esp_dt_cadastro { get; set; }

    public Nullable<System.DateTime> esp_dt_alteracao { get; set; }

}

}
