
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tb_conta
{

    public int grau_id { get; set; }

    public string grau_1 { get; set; }

    public string grau_2 { get; set; }

    public string grau_3 { get; set; }

    public string grau_descricao { get; set; }

}

}
