
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tb_conselho_regional
{

    public int cr_id { get; set; }

    public decimal cr_numero { get; set; }

    public string cr_nome { get; set; }

    public short cr_cons_id { get; set; }

    public string cr_cons_uf { get; set; }

    public Nullable<decimal> cr_especialidade_id { get; set; }



    public virtual tb_conselho tb_conselho { get; set; }

}

}
