
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tb_crediario
{

    public int cred_id { get; set; }

    public Nullable<System.DateTime> cred_dt_entrada { get; set; }

    public Nullable<System.DateTime> cred_dt_vencimento { get; set; }

    public Nullable<decimal> cred_vlr_documento { get; set; }

    public Nullable<decimal> cred_vlr_pago { get; set; }

    public Nullable<System.DateTime> cred_dt_liquidacao { get; set; }

    public Nullable<decimal> cred_vlr_liquidacao { get; set; }

    public Nullable<decimal> cred_desconto_liq { get; set; }

    public Nullable<decimal> cred_juros_liq { get; set; }

    public Nullable<decimal> cred_taxa_liq { get; set; }

    public string cred_situacao { get; set; }

    public Nullable<decimal> cred_cpf_cadastro { get; set; }

    public Nullable<System.DateTime> cred_dt_alteracao { get; set; }

    public Nullable<decimal> cred_cpf_alteracao { get; set; }

    public Nullable<int> cnv_id { get; set; }

    public Nullable<long> cli_id { get; set; }

    public Nullable<int> uneg_id { get; set; }

    public Nullable<int> venda_pdv { get; set; }

    public Nullable<int> venda_id { get; set; }

    public Nullable<System.DateTime> venda_data { get; set; }

    public int rec_id { get; set; }



    public virtual tb_cliente tb_cliente { get; set; }

    public virtual tb_convenio tb_convenio { get; set; }

    public virtual tb_unid_negocio tb_unid_negocio { get; set; }

}

}
