
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tb_convenio
{

    public tb_convenio()
    {

        this.tb_crediario = new HashSet<tb_crediario>();

        this.tb_funcionario = new HashSet<tb_funcionario>();

        this.tb_parametro_descconv = new HashSet<tb_parametro_descconv>();

        this.tbr_convenio_cliente = new HashSet<tbr_convenio_cliente>();

        this.tbr_convenio_finalizadora_sub = new HashSet<tbr_convenio_finalizadora_sub>();

        this.tbr_convenio_un = new HashSet<tbr_convenio_un>();

        this.tb_promocao = new HashSet<tb_promocao>();

    }


    public int cnv_id { get; set; }

    public string cnv_titulo { get; set; }

    public Nullable<decimal> cnv_dia_fechamento { get; set; }

    public Nullable<decimal> cnv_tipo { get; set; }

    public string cnv_tipo_pagamento { get; set; }

    public string cnv_situacao { get; set; }

    public Nullable<System.DateTime> cnv_dt_cadastro { get; set; }

    public Nullable<System.DateTime> cnv_dt_alteracao { get; set; }

    public Nullable<int> prazo_id { get; set; }

    public Nullable<long> cli_id { get; set; }

    public Nullable<int> cnv_codpbm { get; set; }



    public virtual tb_cliente tb_cliente { get; set; }

    public virtual tb_financeiro_prazo tb_financeiro_prazo { get; set; }

    public virtual ICollection<tb_crediario> tb_crediario { get; set; }

    public virtual ICollection<tb_funcionario> tb_funcionario { get; set; }

    public virtual ICollection<tb_parametro_descconv> tb_parametro_descconv { get; set; }

    public virtual ICollection<tbr_convenio_cliente> tbr_convenio_cliente { get; set; }

    public virtual ICollection<tbr_convenio_finalizadora_sub> tbr_convenio_finalizadora_sub { get; set; }

    public virtual ICollection<tbr_convenio_un> tbr_convenio_un { get; set; }

    public virtual ICollection<tb_promocao> tb_promocao { get; set; }

}

}
