
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tb_checkin
{

    public int uneg_id { get; set; }

    public int chkin_pdv { get; set; }

    public int chkin_id { get; set; }

    public System.DateTime chkin_data { get; set; }

    public Nullable<decimal> chkin_num_nf { get; set; }

    public Nullable<int> chkin_operador_id { get; set; }

    public Nullable<int> cmp_id { get; set; }

    public Nullable<int> pedc_id { get; set; }

    public Nullable<int> fab_id { get; set; }

    public Nullable<int> div_id { get; set; }

}

}
