
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tb_checkout
{

    public int uneg_id { get; set; }

    public int chkout_pdv { get; set; }

    public int chkout_id { get; set; }

    public System.DateTime chkout_data { get; set; }

    public Nullable<decimal> chkout_num_nf { get; set; }

    public Nullable<int> chkout_operador_id { get; set; }

    public Nullable<int> cli_id { get; set; }

    public Nullable<int> pedv_id { get; set; }

}

}
