
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tb_crm
{

    public tb_crm()
    {

        this.tb_crm_endereco = new HashSet<tb_crm_endereco>();

    }


    public int crm_id { get; set; }

    public string crm_tipo { get; set; }

    public int uf_id { get; set; }

    public string crm_nome { get; set; }

    public string crm_crm { get; set; }

    public string crm_email { get; set; }

    public string crm_sexo { get; set; }

    public Nullable<System.DateTime> crm_dt_nascimento { get; set; }

    public string crm_celular { get; set; }

    public string crm_obs { get; set; }

    public string crm_situacao { get; set; }

    public Nullable<System.DateTime> crm_dt_cadastro { get; set; }

    public Nullable<System.DateTime> crm_dt_alteracao { get; set; }

    public string crm_cpf_alteracao { get; set; }

    public Nullable<int> esp_id { get; set; }



    public virtual ICollection<tb_crm_endereco> tb_crm_endereco { get; set; }

    public virtual tb_uf tb_uf { get; set; }

}

}
