
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tb_dav_itens____
{

    public int davi_id { get; set; }

    public int dav_id { get; set; }

    public string davi_codigo { get; set; }

    public string davi_descricao { get; set; }

    public decimal davi_quantidade { get; set; }

    public string davi_embalagem { get; set; }

    public decimal davi_valor_unitario { get; set; }

    public decimal davi_valor_desconto { get; set; }

    public decimal davi_valor_acrescimo { get; set; }

    public decimal davi_total_liquido { get; set; }

    public string davi_situacao_tributaria { get; set; }

    public int davi_aliquota { get; set; }

    public string davi_indicador_cancelamento { get; set; }

    public int davi_decimais_quantidade { get; set; }

    public int davi_decimais_vlr_unitario { get; set; }



    public virtual tb_dav tb_dav { get; set; }

}

}
