
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tb_empresa_recarga
{

    public tb_empresa_recarga()
    {

        this.tb_recarga = new HashSet<tb_recarga>();

    }


    public int emprec_id { get; set; }

    public string emprec_nome { get; set; }

    public string emprec_contato { get; set; }

    public string emprec_telefones { get; set; }

    public Nullable<decimal> emprec_perc_comissao { get; set; }

    public string emprec_situacao { get; set; }

    public Nullable<System.DateTime> emprec_dt_cadastro { get; set; }

    public Nullable<System.DateTime> emprec_dt_alteracao { get; set; }

    public Nullable<decimal> emprec_cpf_alteracao { get; set; }

    public int prazo_id { get; set; }

    public int fab_id { get; set; }

    public int div_id { get; set; }



    public virtual tb_financeiro_prazo tb_financeiro_prazo { get; set; }

    public virtual tb_fornecedor_divisao tb_fornecedor_divisao { get; set; }

    public virtual ICollection<tb_recarga> tb_recarga { get; set; }

}

}
