
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tb_entrega_arearisco
{

    public int arearisco_id { get; set; }

    public string arearisco_descricao { get; set; }

    public Nullable<decimal> arearisco_cep_inicial { get; set; }

    public Nullable<decimal> arearisco_cep_final { get; set; }

    public Nullable<decimal> arearisco_nu_inicial { get; set; }

    public Nullable<decimal> arearisco_nu_final { get; set; }

    public string arearisco_mensagem { get; set; }

    public Nullable<decimal> arearisco_acao { get; set; }

    public string arearisco_situacao { get; set; }

    public Nullable<System.DateTime> arearisco_dt_cadastro { get; set; }

    public Nullable<System.DateTime> arearisco_dt_alteracao { get; set; }

    public Nullable<decimal> arearisco_cpf_alteracao { get; set; }

}

}
