
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tb_entrega_rota
{

    public int rota_id { get; set; }

    public int quadra_id { get; set; }

    public string rota_descricao { get; set; }

    public string rota_situacao { get; set; }

    public Nullable<System.DateTime> rota_dt_cadastro { get; set; }

    public Nullable<System.DateTime> rota_dt_alteracao { get; set; }

    public Nullable<decimal> rota_cpf_alteracao { get; set; }

}

}
