
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tb_entrega_rota_cep
{

    public int cep_id { get; set; }

    public int rota_id { get; set; }

    public Nullable<decimal> cep_inicial { get; set; }

    public Nullable<decimal> cep_final { get; set; }

    public Nullable<decimal> cep_nu_inicial { get; set; }

    public Nullable<decimal> cep_nu_final { get; set; }

    public string cep_situacao { get; set; }

    public Nullable<System.DateTime> cep_dt_cadastro { get; set; }

    public Nullable<System.DateTime> cep_dt_alteracao { get; set; }

    public Nullable<decimal> cep_cpf_alteracao { get; set; }

}

}
