
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tb_entrega_quadrante
{

    public int quadra_id { get; set; }

    public string quadra_coordenada { get; set; }

    public string quadra_situacao { get; set; }

    public Nullable<System.DateTime> quadra_dt_cadastro { get; set; }

    public Nullable<System.DateTime> quadra_dt_alteracao { get; set; }

    public Nullable<decimal> quadra_cpf_alteracao { get; set; }

}

}
