
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tb_entrega_polo_bairro
{

    public int bairro_id { get; set; }

    public int polo_id { get; set; }

    public string bairro_bairro { get; set; }

    public string bairro_municipio { get; set; }

    public string bairro_estado { get; set; }

    public string bairro_situacao { get; set; }

    public Nullable<System.DateTime> bairro_dt_cadastro { get; set; }

    public Nullable<System.DateTime> bairro_dt_alteracao { get; set; }

    public Nullable<decimal> bairro_cpf_alteracao { get; set; }

    public Nullable<int> rota_id { get; set; }

}

}
