
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tb_entrega_endereco
{

    public int uneg_id { get; set; }

    public int end_pdv { get; set; }

    public int end_id { get; set; }

    public System.DateTime end_data { get; set; }

    public long end_telefone { get; set; }

    public Nullable<int> end_cep { get; set; }

    public string end_tp_logradouro { get; set; }

    public string end_nm_logradouro { get; set; }

    public Nullable<int> end_numero { get; set; }

    public string end_complemento { get; set; }

    public string end_bairro { get; set; }

    public string end_cidade { get; set; }

    public string end_referencia { get; set; }

    public string end_tipo { get; set; }

    public string end_latitude_decimais { get; set; }

    public string end_longitude_decimais { get; set; }

    public string end_situacao { get; set; }

    public Nullable<System.DateTime> end_dt_cadastro { get; set; }

    public Nullable<System.DateTime> end_dt_alteracao { get; set; }

    public string end_cpf_alteracao { get; set; }

    public Nullable<int> uf_id { get; set; }

    public Nullable<long> ibge_codigo { get; set; }

    public Nullable<int> polo_id { get; set; }

    public string end_contato { get; set; }

    public Nullable<bool> end_uso_continuo { get; set; }

    public string end_obs { get; set; }

    public Nullable<System.DateTime> end_dt_ultima_compra { get; set; }



    public virtual tb_unid_negocio tb_unid_negocio { get; set; }

}

}
