
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tb_ecf_dd
{

    public int ecfd_id { get; set; }

    public Nullable<int> final_id { get; set; }

    public string ecf_numero_serie { get; set; }

    public System.DateTime ecfd_dt_movimento { get; set; }

    public string ecfd_coo { get; set; }

    public string ecfd_gnf { get; set; }

    public string ecfd_grg { get; set; }

    public string ecfd_cdc { get; set; }

    public string ecfd_tipo { get; set; }

    public decimal ecfd_valor_pago { get; set; }

    public string ecfd_tipos_lancamento { get; set; }



    public virtual tb_ecf tb_ecf { get; set; }

    public virtual tb_finalizadora tb_finalizadora { get; set; }

}

}
