
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tb_entrega_polo
{

    public int polo_id { get; set; }

    public string polo_descricao { get; set; }

    public string polo_localizacao { get; set; }

    public string polo_situacao { get; set; }

    public Nullable<System.DateTime> polo_dt_cadastro { get; set; }

    public Nullable<System.DateTime> polo_dt_alteracao { get; set; }

    public Nullable<decimal> polo_cpf_alteracao { get; set; }

    public Nullable<int> uneg_id { get; set; }



    public virtual tb_unid_negocio tb_unid_negocio { get; set; }

}

}
