
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tb_financeiro_administradora
{

    public tb_financeiro_administradora()
    {

        this.tb_finalizadora_sub = new HashSet<tb_finalizadora_sub>();

    }


    public int adm_id { get; set; }

    public string adm_nome { get; set; }

    public string adm_situacao { get; set; }

    public Nullable<System.DateTime> adm_dt_cadastro { get; set; }

    public Nullable<System.DateTime> adm_dt_alteracao { get; set; }



    public virtual ICollection<tb_finalizadora_sub> tb_finalizadora_sub { get; set; }

}

}
