
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tb_fornecedor
{

    public tb_fornecedor()
    {

        this.tb_fornecedor_divisao = new HashSet<tb_fornecedor_divisao>();

        this.tb_parametro_descvend = new HashSet<tb_parametro_descvend>();

        this.tbr_dicionario_produto = new HashSet<tbr_dicionario_produto>();

    }


    public int fab_id { get; set; }

    public Nullable<decimal> fab_codigo { get; set; }

    public string fab_razao { get; set; }

    public string fab_fantasia { get; set; }

    public Nullable<decimal> fab_fabricante { get; set; }

    public Nullable<decimal> fab_tipo { get; set; }

    public string fab_nm_arq_envio { get; set; }

    public string fab_nm_arq_retorno { get; set; }

    public string fab_tip_prc_desc { get; set; }

    public string fab_layout_pedido { get; set; }

    public string fab_layout_dicionario { get; set; }

    public string fab_layout_preco { get; set; }

    public string fab_situacao { get; set; }

    public Nullable<System.DateTime> fab_dt_cadastro { get; set; }

    public Nullable<System.DateTime> fab_dt_alteracao { get; set; }



    public virtual ICollection<tb_fornecedor_divisao> tb_fornecedor_divisao { get; set; }

    public virtual ICollection<tb_parametro_descvend> tb_parametro_descvend { get; set; }

    public virtual ICollection<tbr_dicionario_produto> tbr_dicionario_produto { get; set; }

}

}
