
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tb_funcionario_horario
{

    public tb_funcionario_horario()
    {

        this.tb_funcionario = new HashSet<tb_funcionario>();

        this.tb_funcionario1 = new HashSet<tb_funcionario>();

        this.tb_funcionario_horario_item = new HashSet<tb_funcionario_horario_item>();

    }


    public int hora_id { get; set; }

    public string hora_titulo { get; set; }

    public Nullable<bool> hora_desc_dom { get; set; }

    public Nullable<bool> hora_desc_seg { get; set; }

    public Nullable<bool> hora_desc_ter { get; set; }

    public Nullable<bool> hora_desc_qua { get; set; }

    public Nullable<bool> hora_desc_qui { get; set; }

    public Nullable<bool> hora_desc_sex { get; set; }

    public Nullable<bool> hora_desc_sab { get; set; }

    public Nullable<bool> hora_desc_feriado { get; set; }

    public string hora_situacao { get; set; }

    public Nullable<System.DateTime> hora_dt_cadastro { get; set; }

    public Nullable<System.DateTime> hora_dt_alteracao { get; set; }

    public Nullable<decimal> hora_cpf_alteracao { get; set; }



    public virtual ICollection<tb_funcionario> tb_funcionario { get; set; }

    public virtual ICollection<tb_funcionario> tb_funcionario1 { get; set; }

    public virtual ICollection<tb_funcionario_horario_item> tb_funcionario_horario_item { get; set; }

}

}
