
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tb_financeiro_sangria
{

    public int sangriaf_id { get; set; }

    public System.DateTime sangriaf_data { get; set; }

    public decimal sangriaf_valor { get; set; }

    public string sangriaf_observacao { get; set; }

    public string sangriaf_cpf_responsavel { get; set; }

    public string sangriaf_status { get; set; }

    public string sangriaf_cpf_funcionario { get; set; }

    public Nullable<System.DateTime> sangriaf_dt_alteracao { get; set; }

    public string sangriaf_cpf_alteracao { get; set; }

    public int final_id { get; set; }

    public int usr_id { get; set; }

    public string sangriaf_md5 { get; set; }



    public virtual tb_finalizadora tb_finalizadora { get; set; }

    public virtual tb_usuario tb_usuario { get; set; }

}

}
