
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tb_financeiro_bancos
{

    public tb_financeiro_bancos()
    {

        this.tb_funcionario = new HashSet<tb_funcionario>();

        this.tb_venda_pagamento = new HashSet<tb_venda_pagamento>();

        this.tbr_finalizadora_sub_un = new HashSet<tbr_finalizadora_sub_un>();

    }


    public int banco_id { get; set; }

    public Nullable<decimal> banco_codigo { get; set; }

    public string banco_nome { get; set; }

    public string banco_tipo { get; set; }

    public string banco_situacao { get; set; }

    public Nullable<System.DateTime> banco_dt_cadastro { get; set; }

    public Nullable<System.DateTime> banco_dt_alteracao { get; set; }



    public virtual ICollection<tb_funcionario> tb_funcionario { get; set; }

    public virtual ICollection<tb_venda_pagamento> tb_venda_pagamento { get; set; }

    public virtual ICollection<tbr_finalizadora_sub_un> tbr_finalizadora_sub_un { get; set; }

}

}
