
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tb_financeiro_evento
{

    public tb_financeiro_evento()
    {

        this.tb_finalizadora_sub = new HashSet<tb_finalizadora_sub>();

        this.tb_lancto_financeiro = new HashSet<tb_lancto_financeiro>();

        this.tb_tipo_nota = new HashSet<tb_tipo_nota>();

    }


    public int eventf_id { get; set; }

    public string eventf_descricao { get; set; }

    public string eventf_tip_lancto { get; set; }

    public Nullable<bool> eventf_lanc_manual { get; set; }

    public Nullable<bool> eventf_exportar_uneg { get; set; }

    public string eventf_situacao { get; set; }

    public Nullable<System.DateTime> eventf_dt_cadastro { get; set; }

    public Nullable<System.DateTime> eventf_dt_alteracao { get; set; }

    public string eventf_cpf_alteracao { get; set; }

    public Nullable<int> grau1_id { get; set; }

    public Nullable<int> grau2_id { get; set; }

    public Nullable<int> grau3_id { get; set; }



    public virtual ICollection<tb_finalizadora_sub> tb_finalizadora_sub { get; set; }

    public virtual ICollection<tb_lancto_financeiro> tb_lancto_financeiro { get; set; }

    public virtual ICollection<tb_tipo_nota> tb_tipo_nota { get; set; }

}

}
