
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tb_financeiro_prazo
{

    public tb_financeiro_prazo()
    {

        this.tb_convenio = new HashSet<tb_convenio>();

        this.tb_empresa_privatelabel = new HashSet<tb_empresa_privatelabel>();

        this.tb_empresa_recarga = new HashSet<tb_empresa_recarga>();

        this.tb_finalizadora_sub = new HashSet<tb_finalizadora_sub>();

        this.tb_mvto_compra____ = new HashSet<tb_mvto_compra____>();

        this.tb_privatelabel_finalizadora = new HashSet<tb_privatelabel_finalizadora>();

        this.tb_recarga_finalizadora = new HashSet<tb_recarga_finalizadora>();

        this.tb_venda_pagamento = new HashSet<tb_venda_pagamento>();

        this.tbr_convenio_cliente = new HashSet<tbr_convenio_cliente>();

    }


    public int prazo_id { get; set; }

    public string prazo_titulo { get; set; }

    public Nullable<decimal> prazo_tipo { get; set; }

    public Nullable<decimal> prazo_qtd_meses { get; set; }

    public Nullable<decimal> prazo_qtd_dias { get; set; }

    public Nullable<decimal> prazo_fora_a { get; set; }

    public Nullable<decimal> prazo_nu_parcelas { get; set; }

    public Nullable<bool> prazo_entrada { get; set; }

    public Nullable<decimal> prazo_intervalo_dias { get; set; }

    public Nullable<decimal> prazo_nu_retorno_tef { get; set; }

    public Nullable<bool> prazo_inibe_promocao { get; set; }

    public Nullable<bool> prazo_pratica_pmc { get; set; }

    public string prazo_situacao { get; set; }

    public Nullable<System.DateTime> prazo_dt_cadastro { get; set; }

    public Nullable<System.DateTime> prazo_dt_alteracao { get; set; }



    public virtual ICollection<tb_convenio> tb_convenio { get; set; }

    public virtual ICollection<tb_empresa_privatelabel> tb_empresa_privatelabel { get; set; }

    public virtual ICollection<tb_empresa_recarga> tb_empresa_recarga { get; set; }

    public virtual ICollection<tb_finalizadora_sub> tb_finalizadora_sub { get; set; }

    public virtual ICollection<tb_mvto_compra____> tb_mvto_compra____ { get; set; }

    public virtual ICollection<tb_privatelabel_finalizadora> tb_privatelabel_finalizadora { get; set; }

    public virtual ICollection<tb_recarga_finalizadora> tb_recarga_finalizadora { get; set; }

    public virtual ICollection<tb_venda_pagamento> tb_venda_pagamento { get; set; }

    public virtual ICollection<tbr_convenio_cliente> tbr_convenio_cliente { get; set; }

}

}
