
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tb_funcionario_visitante
{

    public int funcvisit_id { get; set; }

    public Nullable<System.DateTime> funcvisit_dt_visita { get; set; }

    public string funcvisit_situacao { get; set; }

    public Nullable<System.DateTime> funcvisit_dt_cadastro { get; set; }

    public Nullable<System.DateTime> funcvisit_dt_alteracao { get; set; }

    public Nullable<int> func_id { get; set; }

    public Nullable<int> uneg_id { get; set; }



    public virtual tb_unid_negocio tb_unid_negocio { get; set; }

}

}
