
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tb_fornecedor_divisao
{

    public tb_fornecedor_divisao()
    {

        this.tb_checkin_tmp = new HashSet<tb_checkin_tmp>();

        this.tb_empresa_privatelabel = new HashSet<tb_empresa_privatelabel>();

        this.tb_empresa_recarga = new HashSet<tb_empresa_recarga>();

        this.tb_mvto_compra____ = new HashSet<tb_mvto_compra____>();

        this.tb_parametro_comissao = new HashSet<tb_parametro_comissao>();

        this.tb_parametro_descconv = new HashSet<tb_parametro_descconv>();

        this.tb_parametro_descmax = new HashSet<tb_parametro_descmax>();

        this.tb_parametro_descprod = new HashSet<tb_parametro_descprod>();

        this.tb_parametro_descvend = new HashSet<tb_parametro_descvend>();

        this.tb_parametro_markup = new HashSet<tb_parametro_markup>();

        this.tb_pedido_compra____ = new HashSet<tb_pedido_compra____>();

        this.tb_produto = new HashSet<tb_produto>();

        this.tbr_dicionario_un = new HashSet<tbr_dicionario_un>();

    }


    public int fab_id { get; set; }

    public int div_id { get; set; }

    public string div_nome { get; set; }

    public string div_tip_logradouro { get; set; }

    public string div_logradouro { get; set; }

    public Nullable<decimal> div_numero { get; set; }

    public string div_complemento { get; set; }

    public string div_bairro { get; set; }

    public string div_cidade { get; set; }

    public Nullable<decimal> div_cod_municipio { get; set; }

    public string div_cep { get; set; }

    public string div_uf { get; set; }

    public string div_ddd { get; set; }

    public string div_telefone { get; set; }

    public string div_ramal { get; set; }

    public string div_fax { get; set; }

    public string div_faxramal { get; set; }

    public string div_cnpj { get; set; }

    public Nullable<decimal> div_insc_est { get; set; }

    public string div_nm_represent { get; set; }

    public string div_tel_represent { get; set; }

    public string div_email_represent { get; set; }

    public string div_nm_ger_regional { get; set; }

    public string div_tel_ger_regional { get; set; }

    public string div_email_ger_regional { get; set; }

    public string div_nm_ger_nacional { get; set; }

    public string div_tel_ger_nacional { get; set; }

    public string div_email_ger_nacional { get; set; }

    public string div_tipo_frete { get; set; }

    public Nullable<decimal> div_cond_pgto { get; set; }

    public Nullable<decimal> div_prazo_entrega { get; set; }

    public Nullable<decimal> div_pedido_min { get; set; }

    public Nullable<decimal> div_freq_compra { get; set; }

    public string div_situacao { get; set; }

    public Nullable<System.DateTime> div_dt_cadastro { get; set; }

    public Nullable<System.DateTime> div_dt_alteracao { get; set; }



    public virtual ICollection<tb_checkin_tmp> tb_checkin_tmp { get; set; }

    public virtual ICollection<tb_empresa_privatelabel> tb_empresa_privatelabel { get; set; }

    public virtual ICollection<tb_empresa_recarga> tb_empresa_recarga { get; set; }

    public virtual tb_fornecedor tb_fornecedor { get; set; }

    public virtual ICollection<tb_mvto_compra____> tb_mvto_compra____ { get; set; }

    public virtual ICollection<tb_parametro_comissao> tb_parametro_comissao { get; set; }

    public virtual ICollection<tb_parametro_descconv> tb_parametro_descconv { get; set; }

    public virtual ICollection<tb_parametro_descmax> tb_parametro_descmax { get; set; }

    public virtual ICollection<tb_parametro_descprod> tb_parametro_descprod { get; set; }

    public virtual ICollection<tb_parametro_descvend> tb_parametro_descvend { get; set; }

    public virtual ICollection<tb_parametro_markup> tb_parametro_markup { get; set; }

    public virtual ICollection<tb_pedido_compra____> tb_pedido_compra____ { get; set; }

    public virtual ICollection<tb_produto> tb_produto { get; set; }

    public virtual ICollection<tbr_dicionario_un> tbr_dicionario_un { get; set; }

}

}
