
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tb_hist_sangria____
{

    public int hsang_id { get; set; }

    public System.DateTime hsang_data { get; set; }

    public decimal hsang_cod_caixa { get; set; }

    public Nullable<decimal> hsang_fund_dinh { get; set; }

    public Nullable<decimal> hsang_sang_dinh { get; set; }

    public Nullable<decimal> hsang_sang_cheq { get; set; }

    public Nullable<decimal> hsang_sang_cheP { get; set; }

    public Nullable<decimal> hsang_sang_carv { get; set; }

    public Nullable<decimal> hsang_sang_carp { get; set; }

    public Nullable<decimal> hsang_sang_dev { get; set; }

    public Nullable<decimal> hsang_sang_canc { get; set; }

    public Nullable<decimal> hsang_sang_cext { get; set; }

    public Nullable<decimal> hsang_sang_desp { get; set; }

    public Nullable<decimal> hsang_sang_conv { get; set; }

    public Nullable<decimal> hsang_sang_outr { get; set; }

    public Nullable<decimal> hsang_usr_respons { get; set; }

}

}
