
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tb_ibge
{

    public tb_ibge()
    {

        this.tb_cadastro_contador = new HashSet<tb_cadastro_contador>();

        this.tb_unid_negocio = new HashSet<tb_unid_negocio>();

    }


    public int ibge_codigo { get; set; }

    public int uf_id { get; set; }

    public string ibge_municipio { get; set; }



    public virtual ICollection<tb_cadastro_contador> tb_cadastro_contador { get; set; }

    public virtual tb_uf tb_uf { get; set; }

    public virtual ICollection<tb_unid_negocio> tb_unid_negocio { get; set; }

}

}
