
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tb_ibpt_ax
{

    public long iax_id { get; set; }

    public Nullable<int> iax_tabela { get; set; }

    public Nullable<int> iax_excecoes { get; set; }

    public Nullable<decimal> iax_ncm { get; set; }

    public string iax_ncm_descricao_reduz { get; set; }

    public string iax_ncm_descricao { get; set; }

    public string iax_situacao { get; set; }

    public Nullable<System.DateTime> iax_data_alteracao { get; set; }

    public Nullable<decimal> iax_aliq_nacional { get; set; }

    public Nullable<decimal> iax_aliq_importado { get; set; }

    public Nullable<decimal> iax_aliq_estadual { get; set; }

    public Nullable<decimal> iax_aliq_municipal { get; set; }

    public Nullable<System.DateTime> iax_vigencia_inicio { get; set; }

    public Nullable<System.DateTime> iax_vigencia_fim { get; set; }

    public string iax_fonte { get; set; }

    public string iax_chave { get; set; }

    public string iax_versao { get; set; }

}

}
