
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tb_liquidacao_forma
{

    public int formaliq_id { get; set; }

    public string formaliq_descricao { get; set; }

    public Nullable<decimal> formaliq_cpmf { get; set; }

    public string formaliq_tipo { get; set; }

    public string formaliq_infor_cheque { get; set; }

    public string formaliq_situacao { get; set; }

    public Nullable<System.DateTime> formaliq_dt_cadastro { get; set; }

    public Nullable<System.DateTime> formaliq_dt_alteracao { get; set; }

}

}
