
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tb_liquidacao_motivo
{

    public int motivoliq_id { get; set; }

    public string motivoliq_descricao { get; set; }

    public string motivoliq_situacao { get; set; }

    public Nullable<System.DateTime> motivoliq_dt_cadastro { get; set; }

    public Nullable<System.DateTime> motivoliq_dt_alteracao { get; set; }

}

}
