
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tb_mvto_compra____
{

    public tb_mvto_compra____()
    {

        this.tb_mvto_compra_item_divergencia____ = new HashSet<tb_mvto_compra_item_divergencia____>();

        this.tb_mvto_compra_item____ = new HashSet<tb_mvto_compra_item____>();

        this.tbr_mvto_compra_cfop____ = new HashSet<tbr_mvto_compra_cfop____>();

        this.tbr_mvto_compra_dup____ = new HashSet<tbr_mvto_compra_dup____>();

    }


    public int cmp_id { get; set; }

    public Nullable<decimal> cmp_num_nf { get; set; }

    public Nullable<System.DateTime> cmp_dt_entrada { get; set; }

    public Nullable<System.DateTime> cmp_dt_emissao { get; set; }

    public Nullable<decimal> cmp_vlr_produtos { get; set; }

    public Nullable<decimal> cmp_vlr_nota { get; set; }

    public Nullable<decimal> cmp_vlr_informado { get; set; }

    public Nullable<decimal> cmp_desc_comercial { get; set; }

    public Nullable<decimal> cmp_desc_financeiro { get; set; }

    public Nullable<decimal> cmp_vlr_frete { get; set; }

    public Nullable<decimal> cmp_vlr_seguro { get; set; }

    public Nullable<decimal> cmp_vlr_ipi { get; set; }

    public Nullable<decimal> cmp_base_icms_st { get; set; }

    public Nullable<decimal> cmp_vlr_icms_st { get; set; }

    public Nullable<decimal> cmp_vlr_icms { get; set; }

    public Nullable<decimal> cmp_base_icms { get; set; }

    public Nullable<decimal> cmp_vlr_repasse { get; set; }

    public Nullable<decimal> cmp_vlr_encargos { get; set; }

    public Nullable<decimal> cmp_vlr_bonificacao { get; set; }

    public string cmp_observacao { get; set; }

    public Nullable<bool> cmp_duplicata { get; set; }

    public Nullable<decimal> cmp_qtde_itens { get; set; }

    public Nullable<decimal> cmp_cd_operador { get; set; }

    public string cmp_situacao { get; set; }

    public Nullable<System.DateTime> cmp_dt_alteracao { get; set; }

    public Nullable<decimal> cmp_cpf_alteracao { get; set; }

    public Nullable<int> uneg_id { get; set; }

    public Nullable<int> tipnota_id { get; set; }

    public Nullable<int> transp_id { get; set; }

    public Nullable<int> fab_id { get; set; }

    public Nullable<int> div_id { get; set; }

    public Nullable<int> serient_id { get; set; }

    public Nullable<int> uf_id { get; set; }

    public Nullable<int> chkin_id { get; set; }

    public Nullable<int> prazo_id { get; set; }



    public virtual tb_financeiro_prazo tb_financeiro_prazo { get; set; }

    public virtual tb_fornecedor_divisao tb_fornecedor_divisao { get; set; }

    public virtual ICollection<tb_mvto_compra_item_divergencia____> tb_mvto_compra_item_divergencia____ { get; set; }

    public virtual ICollection<tb_mvto_compra_item____> tb_mvto_compra_item____ { get; set; }

    public virtual tb_serie_nota tb_serie_nota { get; set; }

    public virtual tb_uf tb_uf { get; set; }

    public virtual tb_unid_negocio tb_unid_negocio { get; set; }

    public virtual tb_tipo_nota tb_tipo_nota { get; set; }

    public virtual tb_transportadora tb_transportadora { get; set; }

    public virtual ICollection<tbr_mvto_compra_cfop____> tbr_mvto_compra_cfop____ { get; set; }

    public virtual ICollection<tbr_mvto_compra_dup____> tbr_mvto_compra_dup____ { get; set; }

}

}
