
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tb_mvto_compra_item_lote____
{

    public int cmp_id { get; set; }

    public int icmp_id { get; set; }

    public int loteicmp_id { get; set; }

    public string loteicmp_numero { get; set; }

    public Nullable<decimal> loteicmp_qtde { get; set; }

    public Nullable<System.DateTime> loteicmp_validade { get; set; }



    public virtual tb_mvto_compra_item____ tb_mvto_compra_item____ { get; set; }

}

}
