
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tb_mvto_fin____
{

    public int mvtof_id { get; set; }

    public System.DateTime mvtof_data { get; set; }

    public decimal mvtof_cod_caixa { get; set; }

    public Nullable<decimal> mvtof_valor { get; set; }

    public Nullable<decimal> mvtof_usr_respons { get; set; }

    public string mvtof_historico { get; set; }

    public Nullable<decimal> mvtof_usr_mat { get; set; }

}

}
