
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tb_mvto_compra_item_divergencia____
{

    public int divicmp_id { get; set; }

    public int cmp_id { get; set; }

    public int pro_id { get; set; }

    public string divicmp_tipo { get; set; }

    public Nullable<decimal> divicmp_qtde { get; set; }

    public Nullable<decimal> divicmp_custo { get; set; }

    public string divicmp_justificativa { get; set; }



    public virtual tb_mvto_compra____ tb_mvto_compra____ { get; set; }

}

}
