
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tb_nfe_item
{

    public int uneg_id { get; set; }

    public int nfe_pdv { get; set; }

    public int nfe_id { get; set; }

    public System.DateTime nfe_data { get; set; }

    public int infe_id { get; set; }

    public Nullable<decimal> infe_qtd_checkin { get; set; }

    public Nullable<decimal> infe_qtd_pedida { get; set; }

    public Nullable<decimal> infe_qtd_nota { get; set; }

    public string infe_lote_numero { get; set; }

    public Nullable<System.DateTime> infe_lote_validade { get; set; }

    public Nullable<System.DateTime> infe_lote_fabricacao { get; set; }

    public Nullable<decimal> infe_lote_vlr_pmc { get; set; }

    public Nullable<decimal> infe_custo_unit_ped { get; set; }

    public Nullable<decimal> infe_custo_unit_prod { get; set; }

    public Nullable<decimal> infe_custo_unit_nota { get; set; }

    public Nullable<decimal> infe_custo_unit_cont { get; set; }

    public Nullable<decimal> infe_preco_padrao { get; set; }

    public Nullable<decimal> infe_preco_praticado { get; set; }

    public Nullable<decimal> infe_custo_medio { get; set; }

    public Nullable<decimal> infe_tot_custo_ped { get; set; }

    public Nullable<decimal> infe_tot_custo_prod { get; set; }

    public Nullable<decimal> infe_tot_custo_nota { get; set; }

    public Nullable<decimal> infe_tot_custo_cont { get; set; }

    public Nullable<decimal> infe_tot_preco_padrao { get; set; }

    public Nullable<decimal> infe_tot_preco_praticado { get; set; }

    public Nullable<decimal> infe_tot_custo_medio { get; set; }

    public Nullable<decimal> infe_qtd_bonificacao { get; set; }

    public Nullable<decimal> infe_vlr_bonificacao { get; set; }

    public Nullable<decimal> infe_vlr_encfin { get; set; }

    public Nullable<decimal> infe_vlr_desconto { get; set; }

    public Nullable<decimal> infe_vlr_frete { get; set; }

    public Nullable<decimal> infe_vlr_descfin { get; set; }

    public Nullable<decimal> infe_vlr_repassse { get; set; }

    public Nullable<decimal> infe_vlr_comissao { get; set; }

    public Nullable<int> infe_Num_Pedido { get; set; }

    public Nullable<int> infe_icms_orig { get; set; }

    public Nullable<int> infe_icms_cst { get; set; }

    public Nullable<int> infe_icms_modbc { get; set; }

    public Nullable<decimal> infe_icms_predbc { get; set; }

    public Nullable<decimal> infe_icms_vbc { get; set; }

    public Nullable<decimal> infe_icms_picms { get; set; }

    public Nullable<decimal> infe_icms_vicms { get; set; }

    public Nullable<int> infe_icms_modbst { get; set; }

    public Nullable<decimal> infe_icms_pmvast { get; set; }

    public Nullable<decimal> infe_icms_predbcst { get; set; }

    public Nullable<decimal> infe_icms_vbcst { get; set; }

    public Nullable<decimal> infe_icms_picmsst { get; set; }

    public Nullable<decimal> infe_icms_vicmsst { get; set; }

    public Nullable<decimal> infe_icms_vbstret { get; set; }

    public Nullable<decimal> infe_icms_vicmsstret { get; set; }

    public Nullable<decimal> infe_qcom { get; set; }

    public Nullable<decimal> infe_vuncom { get; set; }

    public Nullable<decimal> infe_vprod { get; set; }

    public Nullable<decimal> infe_vdesc { get; set; }

    public Nullable<decimal> infe_vprodcont { get; set; }

    public Nullable<int> infe_ipi_cenq { get; set; }

    public Nullable<int> infe_ipi_cst { get; set; }

    public Nullable<decimal> infe_ipi_pipi { get; set; }

    public Nullable<decimal> infe_ipi_vipi { get; set; }

    public Nullable<int> infe_pis_cst { get; set; }

    public Nullable<decimal> infe_pis_vbcpis { get; set; }

    public Nullable<decimal> infe_pis_ppis { get; set; }

    public Nullable<decimal> infe_pis_vpis { get; set; }

    public Nullable<int> infe_cofins_cst { get; set; }

    public Nullable<decimal> infe_cofins_vbccofins { get; set; }

    public Nullable<decimal> infe_cofins_pcofins { get; set; }

    public Nullable<decimal> infe_cofins_vcofiins { get; set; }

    public Nullable<decimal> infe_voutro { get; set; }

    public Nullable<decimal> infe_vdescfin { get; set; }

    public Nullable<int> pro_id { get; set; }

    public Nullable<int> cfop_id { get; set; }



    public virtual tb_cfop tb_cfop { get; set; }

    public virtual tb_nfe tb_nfe { get; set; }

    public virtual tb_produto tb_produto { get; set; }

}

}
