
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tb_nfe_danfe
{

    public int uneg_id { get; set; }

    public int nfe_pdv { get; set; }

    public int nfe_id { get; set; }

    public System.DateTime nfe_data { get; set; }

    public string danfe_chave_acesso { get; set; }

    public string danfe_xml { get; set; }

    public string danfe_txt { get; set; }

}

}
