
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tb_nfe
{

    public tb_nfe()
    {

        this.tb_nfe_item = new HashSet<tb_nfe_item>();

    }


    public int uneg_id { get; set; }

    public int nfe_pdv { get; set; }

    public int nfe_id { get; set; }

    public System.DateTime nfe_data { get; set; }

    public Nullable<int> nfe_id_vendedor { get; set; }

    public Nullable<int> nfe_id_atendente { get; set; }

    public Nullable<int> nfe_id_cancelado { get; set; }

    public string nfe_chave_acesso { get; set; }

    public string nfe_situacao { get; set; }

    public string nfe_uf_origem { get; set; }

    public string nfe_uf_destino { get; set; }

    public Nullable<decimal> nfe_numero { get; set; }

    public Nullable<decimal> nfe_cfop { get; set; }

    public Nullable<decimal> nfe_nat_operacao { get; set; }

    public string nfe_modelo { get; set; }

    public Nullable<decimal> nfe_serie { get; set; }

    public string nfe_tipo { get; set; }

    public Nullable<decimal> nfe_cod_municipio { get; set; }

    public string nfe_data_saida { get; set; }

    public string nfe_hora_saida { get; set; }

    public Nullable<int> nfe_itens_produto { get; set; }

    public Nullable<decimal> nfe_qtd_produto { get; set; }

    public Nullable<decimal> nfe_total_venda { get; set; }

    public Nullable<decimal> nfe_total_venda_padrao { get; set; }

    public Nullable<decimal> nfe_total_venda_praticado { get; set; }

    public Nullable<decimal> nfe_total_venda_real { get; set; }

    public Nullable<decimal> nfe_total_custo { get; set; }

    public Nullable<decimal> nfe_total_bonificado { get; set; }

    public Nullable<decimal> nfe_total_comissao { get; set; }

    public Nullable<decimal> nfe_desc_comercial { get; set; }

    public Nullable<decimal> nfe_desc_financeiro { get; set; }

    public Nullable<decimal> nfe_icmstot_vbc { get; set; }

    public Nullable<decimal> nfe_icmstot_vicms { get; set; }

    public Nullable<decimal> nfe_icmstot_vst { get; set; }

    public Nullable<decimal> nfe_icmstot_vprod { get; set; }

    public Nullable<decimal> nfe_icmstot_vfrete { get; set; }

    public Nullable<decimal> nfe_icmstot_vseg { get; set; }

    public Nullable<decimal> nfe_icmstot_vdesc { get; set; }

    public Nullable<decimal> nfe_icmstot_vii { get; set; }

    public Nullable<decimal> nfe_icmstot_vipi { get; set; }

    public Nullable<decimal> nfe_icmstot_vpis { get; set; }

    public Nullable<decimal> nfe_icmstot_vcofins { get; set; }

    public Nullable<decimal> nfe_icmstot_voutros { get; set; }

    public Nullable<decimal> nfe_icmstot_vnf { get; set; }

    public Nullable<decimal> nfe_vlr_totaltrib { get; set; }

    public Nullable<decimal> nfe_issqntot_vserv { get; set; }

    public Nullable<decimal> nfe_issqntot_vbc { get; set; }

    public Nullable<decimal> nfe_issqntot_viss { get; set; }

    public Nullable<decimal> nfe_issqntot_vpis { get; set; }

    public Nullable<decimal> nfe_issqntot_vcofins { get; set; }

    public Nullable<decimal> nfe_rettrib_vretpis { get; set; }

    public Nullable<decimal> nfe_rettrib_vretcofins { get; set; }

    public Nullable<decimal> nfe_rettrib_vretcsll { get; set; }

    public Nullable<decimal> nfe_rettrib_vbcirrf { get; set; }

    public Nullable<decimal> nfe_rettrib_virrf { get; set; }

    public Nullable<decimal> nfe_rettrib_vbcretprev { get; set; }

    public Nullable<decimal> nfe_rettrib_vretprev { get; set; }

    public Nullable<decimal> nfe_vlr_isento { get; set; }

    public string nfe_nf_obs { get; set; }

    public string nfe_tip_frete { get; set; }

    public string nfe_destino { get; set; }

    public Nullable<decimal> nfe_peso_l { get; set; }

    public Nullable<decimal> nfe_peso_b { get; set; }

    public string nfe_placa_veiculo { get; set; }

    public Nullable<decimal> nfe_transportadora { get; set; }

    public string nfe_dispositivo { get; set; }

    public string nfe_refecf_mod { get; set; }

    public Nullable<int> nfe_refecf_necf { get; set; }

    public Nullable<int> nfe_refecf_coo { get; set; }

    public Nullable<int> transp_id { get; set; }

    public Nullable<int> pedv_id { get; set; }

    public Nullable<long> cli_id { get; set; }

    public Nullable<int> cnv_id { get; set; }

    public Nullable<int> serient_id { get; set; }

    public Nullable<int> enft_id { get; set; }

    public Nullable<int> venda_ecf_pdv { get; set; }

    public Nullable<int> venda_ecf_id { get; set; }

    public Nullable<System.DateTime> venda_ecf_data { get; set; }



    public virtual ICollection<tb_nfe_item> tb_nfe_item { get; set; }

}

}
