
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tb_princ_ativo
{

    public int pat_id { get; set; }

    public string pat_descricao { get; set; }

    public System.DateTime pat_dt_alteracao { get; set; }

}

}
