
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tb_produto_piscofins
{

    public tb_produto_piscofins()
    {

        this.tb_produto = new HashSet<tb_produto>();

    }


    public string piscofins_cod { get; set; }

    public string piscofins_legenda { get; set; }

    public string piscofins_situacao { get; set; }

    public Nullable<System.DateTime> piscofins_dt_cadastro { get; set; }

    public Nullable<System.DateTime> piscofins_dt_alteracao { get; set; }



    public virtual ICollection<tb_produto> tb_produto { get; set; }

}

}
