
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tb_produto_familia
{

    public tb_produto_familia()
    {

        this.tb_parametro_descvend = new HashSet<tb_parametro_descvend>();

        this.tb_produto_fam_grupo = new HashSet<tb_produto_fam_grupo>();

    }


    public int fam_id { get; set; }

    public string fam_descricao { get; set; }

    public string fam_situacao { get; set; }

    public Nullable<System.DateTime> fam_dt_cadastro { get; set; }

    public Nullable<System.DateTime> fam_dt_alteracao { get; set; }



    public virtual ICollection<tb_parametro_descvend> tb_parametro_descvend { get; set; }

    public virtual ICollection<tb_produto_fam_grupo> tb_produto_fam_grupo { get; set; }

}

}
