
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tb_pedido_compra____
{

    public tb_pedido_compra____()
    {

        this.tb_checkin_tmp = new HashSet<tb_checkin_tmp>();

        this.tb_pedido_compra_item____ = new HashSet<tb_pedido_compra_item____>();

    }


    public int pedc_id { get; set; }

    public Nullable<decimal> pedc_nu_nf { get; set; }

    public Nullable<System.DateTime> pedc_dt_pedido { get; set; }

    public Nullable<System.DateTime> pedc_dt_emissao { get; set; }

    public Nullable<System.DateTime> pedc_dt_vencimento { get; set; }

    public Nullable<decimal> pedc_vlr_total { get; set; }

    public Nullable<decimal> pedc_qtd_itens { get; set; }

    public Nullable<decimal> pedc_vlr_desconto { get; set; }

    public string pedc_situacao { get; set; }

    public Nullable<int> uneg_id { get; set; }

    public Nullable<int> ped_id { get; set; }

    public Nullable<int> fab_id { get; set; }

    public Nullable<int> div_id { get; set; }

    public Nullable<System.DateTime> pedc_dt_alteracao { get; set; }



    public virtual ICollection<tb_checkin_tmp> tb_checkin_tmp { get; set; }

    public virtual tb_fornecedor_divisao tb_fornecedor_divisao { get; set; }

    public virtual ICollection<tb_pedido_compra_item____> tb_pedido_compra_item____ { get; set; }

    public virtual tb_unid_negocio tb_unid_negocio { get; set; }

}

}
