
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tb_produto_fam_categoria
{

    public tb_produto_fam_categoria()
    {

        this.tb_parametro_descvend = new HashSet<tb_parametro_descvend>();

        this.tb_produto_fam_categ_sub = new HashSet<tb_produto_fam_categ_sub>();

    }


    public int fam_id { get; set; }

    public int grp_id { get; set; }

    public int cat_id { get; set; }

    public string cat_descricao { get; set; }

    public string cat_situacao { get; set; }

    public Nullable<System.DateTime> cat_dt_cadastro { get; set; }

    public Nullable<System.DateTime> cat_dt_alteracao { get; set; }



    public virtual ICollection<tb_parametro_descvend> tb_parametro_descvend { get; set; }

    public virtual ICollection<tb_produto_fam_categ_sub> tb_produto_fam_categ_sub { get; set; }

    public virtual tb_produto_fam_grupo tb_produto_fam_grupo { get; set; }

}

}
