
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tb_produto_princativo
{

    public tb_produto_princativo()
    {

        this.tb_produto = new HashSet<tb_produto>();

    }


    public int pat_id { get; set; }

    public string pat_descricao { get; set; }

    public string pat_situacao { get; set; }

    public Nullable<System.DateTime> pat_dt_cadastro { get; set; }

    public Nullable<System.DateTime> pat_dt_alteracao { get; set; }

    public Nullable<decimal> pat_cpf_alteracao { get; set; }



    public virtual ICollection<tb_produto> tb_produto { get; set; }

}

}
