
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tb_parametro_limpezas
{

    public int tb_id { get; set; }

    public Nullable<System.DateTime> tb_dt_alteracao { get; set; }

    public Nullable<decimal> tb_cpf_alteracao { get; set; }

    public Nullable<System.DateTime> tb_data_exec { get; set; }

    public Nullable<int> LJ_tb_abertura_caixa { get; set; }

    public Nullable<int> LJ_tb_checkin { get; set; }

    public Nullable<int> LJ_tb_checkout { get; set; }

    public Nullable<int> LJ_tb_abcfarma_periodo { get; set; }

    public Nullable<int> LJ_tb_sangrias { get; set; }

    public Nullable<int> LJ_tb_suprimentos { get; set; }

    public Nullable<int> LJ_tb_reducao_z { get; set; }

    public Nullable<int> LJ_tb_venda { get; set; }

    public Nullable<int> LJ_tb_promocao { get; set; }

    public Nullable<int> LJ_tb_ponto { get; set; }

    public Nullable<int> LJ_tb_nfe { get; set; }

    public Nullable<int> LJ_tb_privatelabel { get; set; }

    public Nullable<int> LJ_tb_recarga { get; set; }

    public Nullable<int> LJ_tb_lancto_financeiro { get; set; }

    public Nullable<int> LJ_tb_agenda_produto { get; set; }

    public Nullable<int> LJ_tb_crediario { get; set; }

}

}
