
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tb_parametro
{

    public int par_loja { get; set; }

    public int par_pdv { get; set; }

    public string par_msgRodape { get; set; }

    public int par_ponto_tempoSeguranca { get; set; }

    public int par_ponto_tempoAprovGerenteEntrada { get; set; }

    public int par_ponto_tempoAprovGerenteAlmoco { get; set; }

    public int par_ponto_tempoAprovGerenteVoltaAlmoco { get; set; }

    public int par_ponto_tempoAprovGerenteSaida { get; set; }

    public Nullable<int> par_ponto_meridianoMinutos { get; set; }

}

}
