
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tb_ponto
{

    public int ponto_id { get; set; }

    public System.DateTime ponto_dt_ponto { get; set; }

    public Nullable<System.DateTime> ponto_hr_entrada { get; set; }

    public Nullable<System.DateTime> ponto_hr_almoco_inicio { get; set; }

    public Nullable<System.DateTime> ponto_hr_almoco_fim { get; set; }

    public Nullable<System.DateTime> ponto_hr_saida { get; set; }

    public int func_id { get; set; }

    public Nullable<int> motivo_id { get; set; }

    public Nullable<int> usr_id { get; set; }

    public string ponto_situacao { get; set; }



    public virtual tb_ponto_motivo tb_ponto_motivo { get; set; }

    public virtual tb_usuario tb_usuario { get; set; }

}

}
