
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tb_produto_kit
{

    public int pro_id { get; set; }

    public int kitpro_produto { get; set; }

    public Nullable<decimal> kitpro_quantidade { get; set; }

    public string kitpro_situacao { get; set; }

    public Nullable<System.DateTime> kitpro_dt_cadastro { get; set; }

    public Nullable<System.DateTime> kitpro_dt_alteracao { get; set; }

}

}
