
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tb_ponto_motivo
{

    public tb_ponto_motivo()
    {

        this.tb_ponto = new HashSet<tb_ponto>();

    }


    public int motivo_id { get; set; }

    public string motivo_descricao { get; set; }

    public string motivo_situacao { get; set; }



    public virtual ICollection<tb_ponto> tb_ponto { get; set; }

}

}
