
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tb_pedido_compra_item____
{

    public int pedc_id { get; set; }

    public int ipedc_id { get; set; }

    public Nullable<decimal> ipedc_qtd_atendida { get; set; }

    public Nullable<decimal> ipedv_qtd_embalagem { get; set; }

    public Nullable<decimal> ipedc_custo_unitario { get; set; }

    public Nullable<decimal> ipedc_perc_desconto { get; set; }

    public Nullable<int> pro_id { get; set; }

    public string ipedc_situacao { get; set; }



    public virtual tb_pedido_compra____ tb_pedido_compra____ { get; set; }

}

}
