
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tb_piscofins
{

    public int piscofins_id { get; set; }

    public Nullable<decimal> piscofins_cst { get; set; }

    public Nullable<decimal> piscofins_aliq_LP_pis { get; set; }

    public Nullable<decimal> piscofins_aliq_LP_cofins { get; set; }

    public Nullable<decimal> piscofins_aliq_LR_pis { get; set; }

    public Nullable<decimal> piscofins_aliq_LR_cofins { get; set; }

    public string piscofins_situacao { get; set; }

    public Nullable<System.DateTime> piscofins_dt_cadastro { get; set; }

    public Nullable<System.DateTime> piscofins_dt_alteracao { get; set; }

    public Nullable<decimal> piscofins_cpf_alteracao { get; set; }

}

}
