
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tb_produto_barra
{

    public int pro_id { get; set; }

    public decimal barra_codigo { get; set; }

    public string barra_tip_embalagem { get; set; }

    public Nullable<decimal> barra_qtd_embalagem { get; set; }

    public string barra_situacao { get; set; }

    public Nullable<System.DateTime> barra_dt_cadastro { get; set; }

    public Nullable<System.DateTime> barra_dt_alteracao { get; set; }

    public string barra_cpf_alteracao { get; set; }



    public virtual tb_produto tb_produto { get; set; }

}

}
