
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tb_promocao_tipo
{

    public int tippro_id { get; set; }

    public string tippro_descricao { get; set; }

    public string tippro_situacao { get; set; }

    public Nullable<System.DateTime> tippro_dt_cadastro { get; set; }

    public Nullable<System.DateTime> tippro_dt_alteracao { get; set; }

    public Nullable<decimal> tippro_cpf_alteracao { get; set; }

}

}
