
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tb_reducao_z_itens
{

    public int reduz_itens_id { get; set; }

    public string ecf_numero_serie { get; set; }

    public System.DateTime reduz_data_movimento { get; set; }

    public string reduz_itens_sequencia { get; set; }

    public string reduz_itens_tipo { get; set; }

    public Nullable<decimal> reduz_itens_valor { get; set; }

    public Nullable<decimal> reduz_itens_total { get; set; }

    public string reduz_itens_md5 { get; set; }



    public virtual tb_reducao_z tb_reducao_z { get; set; }

}

}
