
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tb_reducao_z
{

    public tb_reducao_z()
    {

        this.tb_reducao_z_itens = new HashSet<tb_reducao_z_itens>();

    }


    public string ecf_numero_serie { get; set; }

    public System.DateTime reduz_data_movimento { get; set; }

    public int reduz_crz { get; set; }

    public int reduz_coo { get; set; }

    public int reduz_cro { get; set; }

    public System.DateTime reduz_data_emissao { get; set; }

    public decimal reduz_venda_bruta { get; set; }

    public decimal reduz_gt { get; set; }

    public string reduz_md5 { get; set; }

    public Nullable<int> uneg_id { get; set; }

    public Nullable<int> ecf_id { get; set; }



    public virtual tb_ecf tb_ecf { get; set; }

    public virtual ICollection<tb_reducao_z_itens> tb_reducao_z_itens { get; set; }

}

}
