
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tb_recarga
{

    public tb_recarga()
    {

        this.tb_recarga_finalizadora = new HashSet<tb_recarga_finalizadora>();

    }


    public int uneg_id { get; set; }

    public int pin_pdv { get; set; }

    public System.DateTime pin_data { get; set; }

    public int pin_id { get; set; }

    public string pin_cod_convenio { get; set; }

    public string pin_nome_convenio { get; set; }

    public string pin_tipo_credito { get; set; }

    public string pin_nome_credito { get; set; }

    public Nullable<decimal> pin_qtde { get; set; }

    public Nullable<decimal> pin_preco { get; set; }

    public Nullable<decimal> pin_tot_pgto { get; set; }

    public string pin_ddd { get; set; }

    public string pin_telefone { get; set; }

    public Nullable<int> pin_operado_cx { get; set; }

    public int emprec_id { get; set; }

    public Nullable<int> pin_ecf { get; set; }

    public Nullable<int> pin_coo { get; set; }

    public Nullable<int> pin_gnf { get; set; }



    public virtual tb_empresa_recarga tb_empresa_recarga { get; set; }

    public virtual ICollection<tb_recarga_finalizadora> tb_recarga_finalizadora { get; set; }

}

}
