
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tb_tipo_nota
{

    public tb_tipo_nota()
    {

        this.tb_mvto_compra____ = new HashSet<tb_mvto_compra____>();

    }


    public int tipnota_id { get; set; }

    public string tipnota_descricao { get; set; }

    public string tipnota_tipo { get; set; }

    public Nullable<bool> tipnota_bonificado_alt_custo { get; set; }

    public string tipnota_tipo_aplicacao_financ { get; set; }

    public Nullable<bool> tipnota_romaneio { get; set; }

    public Nullable<bool> tipnota_obrigar_checkin { get; set; }

    public Nullable<bool> tipnota_obrigar_icms { get; set; }

    public Nullable<bool> tipnota_permitir_alterar_dic { get; set; }

    public Nullable<bool> tipnota_aplicar_preco_rede { get; set; }

    public Nullable<bool> tipnota_desprezar_sngpc { get; set; }

    public Nullable<bool> tipnota_nf_contabil { get; set; }

    public Nullable<decimal> tipnota_ac_qtde_prod_fora_ped { get; set; }

    public string tipnota_acao_custo_maior_vend { get; set; }

    public string tipnota_acao_alterar_prec_vend { get; set; }

    public Nullable<bool> tipnota_obrigar_pedido_compra { get; set; }

    public Nullable<decimal> tipnota_limite_acert_dif_fech { get; set; }

    public Nullable<bool> tipnota_ignora_justif_diverg { get; set; }

    public string tipnota_situacao { get; set; }

    public Nullable<System.DateTime> tipnota_dt_cadastro { get; set; }

    public Nullable<System.DateTime> tipnota_dt_alteracao { get; set; }

    public Nullable<int> cfop_id { get; set; }

    public Nullable<int> cdmvto_codigo { get; set; }

    public Nullable<int> eventf_id { get; set; }



    public virtual tb_cfop tb_cfop { get; set; }

    public virtual tb_financeiro_evento tb_financeiro_evento { get; set; }

    public virtual ICollection<tb_mvto_compra____> tb_mvto_compra____ { get; set; }

    public virtual tb_tipo_mvto_produto tb_tipo_mvto_produto { get; set; }

}

}
