
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tb_uf
{

    public tb_uf()
    {

        this.tb_cliente = new HashSet<tb_cliente>();

        this.tb_cliente_anvisa = new HashSet<tb_cliente_anvisa>();

        this.tb_cliente_endereco = new HashSet<tb_cliente_endereco>();

        this.tb_crm = new HashSet<tb_crm>();

        this.tb_crm_endereco = new HashSet<tb_crm_endereco>();

        this.tb_ibge = new HashSet<tb_ibge>();

        this.tb_mvto_compra____ = new HashSet<tb_mvto_compra____>();

        this.tb_paciente_anvisa = new HashSet<tb_paciente_anvisa>();

        this.tb_unid_negocio = new HashSet<tb_unid_negocio>();

        this.tbr_abcfarma_uf = new HashSet<tbr_abcfarma_uf>();

        this.tbr_produto_tributacao = new HashSet<tbr_produto_tributacao>();

    }


    public int uf_id { get; set; }

    public string uf_sigla { get; set; }

    public string uf_descricao { get; set; }

    public string uf_situacao { get; set; }

    public Nullable<System.DateTime> uf_dt_cadastro { get; set; }

    public Nullable<System.DateTime> uf_dt_alteracao { get; set; }



    public virtual ICollection<tb_cliente> tb_cliente { get; set; }

    public virtual ICollection<tb_cliente_anvisa> tb_cliente_anvisa { get; set; }

    public virtual ICollection<tb_cliente_endereco> tb_cliente_endereco { get; set; }

    public virtual ICollection<tb_crm> tb_crm { get; set; }

    public virtual ICollection<tb_crm_endereco> tb_crm_endereco { get; set; }

    public virtual ICollection<tb_ibge> tb_ibge { get; set; }

    public virtual ICollection<tb_mvto_compra____> tb_mvto_compra____ { get; set; }

    public virtual ICollection<tb_paciente_anvisa> tb_paciente_anvisa { get; set; }

    public virtual tb_uf tb_uf1 { get; set; }

    public virtual tb_uf tb_uf2 { get; set; }

    public virtual ICollection<tb_unid_negocio> tb_unid_negocio { get; set; }

    public virtual ICollection<tbr_abcfarma_uf> tbr_abcfarma_uf { get; set; }

    public virtual ICollection<tbr_produto_tributacao> tbr_produto_tributacao { get; set; }

}

}
