
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tb_usuario_bloqueio
{

    public tb_usuario_bloqueio()
    {

        this.tb_usuario = new HashSet<tb_usuario>();

    }


    public int bloq_id { get; set; }

    public string bloq_descricao { get; set; }

    public string bloq_situacao { get; set; }

    public Nullable<System.DateTime> bloq_dt_cadastro { get; set; }

    public Nullable<System.DateTime> bloq_dt_alteracao { get; set; }



    public virtual ICollection<tb_usuario> tb_usuario { get; set; }

}

}
