
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tb_usuario
{

    public tb_usuario()
    {

        this.tb_agenda_produto = new HashSet<tb_agenda_produto>();

        this.tb_agenda_produto1 = new HashSet<tb_agenda_produto>();

        this.tb_cliente_fiscal = new HashSet<tb_cliente_fiscal>();

        this.tb_financeiro_sangria = new HashSet<tb_financeiro_sangria>();

        this.tb_financeiro_suprimento = new HashSet<tb_financeiro_suprimento>();

        this.tb_parametro_descvend = new HashSet<tb_parametro_descvend>();

        this.tb_ponto = new HashSet<tb_ponto>();

        this.tb_venda_dav = new HashSet<tb_venda_dav>();

        this.tb_venda_prevenda_item = new HashSet<tb_venda_prevenda_item>();

        this.tb_venda_prevenda = new HashSet<tb_venda_prevenda>();

    }


    public int usr_id { get; set; }

    public string usr_cpf { get; set; }

    public string usr_nome { get; set; }

    public string usr_apelido { get; set; }

    public string usr_senha_local { get; set; }

    public Nullable<System.DateTime> usr_senha_tmp { get; set; }

    public Nullable<System.DateTime> usr_dt_alteracao_sync { get; set; }

    public string usr_situacao { get; set; }

    public Nullable<System.DateTime> usr_blq_dt_inicial { get; set; }

    public Nullable<System.DateTime> usr_blq_dt_final { get; set; }

    public Nullable<System.DateTime> usr_dt_cadastro { get; set; }

    public Nullable<System.DateTime> usr_dt_alteracao { get; set; }

    public Nullable<bool> usr_online { get; set; }

    public Nullable<int> grp_id { get; set; }

    public Nullable<int> dpto_id { get; set; }

    public Nullable<int> funcao_id { get; set; }

    public Nullable<int> bloq_id { get; set; }

    public Nullable<int> func_id { get; set; }



    public virtual ICollection<tb_agenda_produto> tb_agenda_produto { get; set; }

    public virtual ICollection<tb_agenda_produto> tb_agenda_produto1 { get; set; }

    public virtual ICollection<tb_cliente_fiscal> tb_cliente_fiscal { get; set; }

    public virtual ICollection<tb_financeiro_sangria> tb_financeiro_sangria { get; set; }

    public virtual ICollection<tb_financeiro_suprimento> tb_financeiro_suprimento { get; set; }

    public virtual ICollection<tb_parametro_descvend> tb_parametro_descvend { get; set; }

    public virtual ICollection<tb_ponto> tb_ponto { get; set; }

    public virtual tb_usuario_bloqueio tb_usuario_bloqueio { get; set; }

    public virtual tb_usuario_dpto tb_usuario_dpto { get; set; }

    public virtual tb_usuario_grupo tb_usuario_grupo { get; set; }

    public virtual tb_usuario_funcao tb_usuario_funcao { get; set; }

    public virtual ICollection<tb_venda_dav> tb_venda_dav { get; set; }

    public virtual ICollection<tb_venda_prevenda_item> tb_venda_prevenda_item { get; set; }

    public virtual ICollection<tb_venda_prevenda> tb_venda_prevenda { get; set; }

}

}
