
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tb_venda_prevenda_pgto
{

    public int vendaPv_id { get; set; }

    public System.DateTime vendaPv_data_preVenda { get; set; }

    public int uneg_id { get; set; }

    public int venda_pdv { get; set; }

    public int vpag_id { get; set; }

    public int final_id { get; set; }

    public int subfin_id { get; set; }

    public Nullable<int> vpag_num_referencia { get; set; }

    public Nullable<decimal> vpag_valor { get; set; }

    public Nullable<decimal> vpag_troco { get; set; }

    public Nullable<bool> vpag_vendatef { get; set; }

    public Nullable<decimal> vpag_valor_compra_saque { get; set; }

    public string vpag_tef_nsu_venda { get; set; }

    public string vpag_tef_nsu_host { get; set; }

    public string vpag_tipo_cartao { get; set; }

    public string vpag_comprovante_cliente { get; set; }

    public string vpag_comprovante_loja { get; set; }

    public string vpag_status { get; set; }

    public Nullable<System.DateTime> vpag_cli_data_ch { get; set; }

    public Nullable<int> vpag_cli_banco_id_ch { get; set; }

    public Nullable<decimal> vpag_cli_agencia_ch { get; set; }

    public Nullable<decimal> vpag_cli_c1_ch { get; set; }

    public Nullable<decimal> vpag_cli_conta_corrente_ch { get; set; }

    public Nullable<decimal> vpag_cli_c2_ch { get; set; }

    public Nullable<decimal> vpag_cli_numero_ch { get; set; }

    public Nullable<decimal> vpag_cli_c3_ch { get; set; }

    public string vpag_cli_doc_troca { get; set; }

    public Nullable<int> prazo_id { get; set; }

    public Nullable<long> cli_id { get; set; }

}

}
