
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tb_venda_dav_item
{

    public int venda_dav_item_id { get; set; }

    public System.DateTime venda_dav_data_preVenda { get; set; }

    public int venda_dav_id { get; set; }

    public int uneg_id { get; set; }

    public int venda_pdv { get; set; }

    public Nullable<int> venda_id { get; set; }

    public Nullable<long> venda_dav_item_autorizacao { get; set; }

    public Nullable<int> venda_dav_item_codigo { get; set; }

    public string venda_dav_item_cpfCnpj { get; set; }

    public string venda_dav_item_descricao { get; set; }

    public string venda_dav_item_ean13 { get; set; }

    public Nullable<bool> venda_dav_item_marcaAgpuc { get; set; }

    public Nullable<decimal> venda_dav_item_preco { get; set; }

    public Nullable<decimal> venda_dav_item_precoPraticado { get; set; }

    public Nullable<decimal> venda_dav_item_precoPadrao { get; set; }

    public Nullable<decimal> venda_dav_item_precoReal { get; set; }

    public Nullable<decimal> venda_dav_item_precoReembolso { get; set; }

    public Nullable<decimal> venda_dav_item_precoVista { get; set; }

    public Nullable<int> venda_dav_item_quantidade { get; set; }

    public Nullable<decimal> venda_dav_item_totalValor { get; set; }

    public Nullable<decimal> venda_dav_item_valorDesconto { get; set; }

    public Nullable<int> venda_dav_item_vendedor_id { get; set; }

    public Nullable<System.DateTime> venda_dav_item_data { get; set; }

    public string venda_dav_item_status { get; set; }

    public Nullable<long> venda_dav_item_cancela_vendedor_id { get; set; }

    public string venda_dav_item_vidaLink { get; set; }

    public Nullable<System.DateTime> venda_dav_item_receita_data { get; set; }

    public string venda_dav_item_receita_notificacao_num { get; set; }

    public string venda_dav_item_receita_notificacao_tipo { get; set; }

    public string venda_dav_item_comprador_nome { get; set; }

    public Nullable<decimal> venda_dav_item_comprador_tipdoc { get; set; }

    public string venda_dav_item_comprador_doc { get; set; }

    public string venda_dav_item_comprador_oexped { get; set; }

    public string venda_dav_item_comprador_uf { get; set; }

    public string venda_dav_item_paciente_doc { get; set; }

    public string venda_dav_item_paciente_nome { get; set; }

    public string venda_dav_item_paciente_sexo { get; set; }

    public Nullable<System.DateTime> venda_dav_item_paciente_dt_nascimento { get; set; }

    public string venda_dav_item_paciente_cid { get; set; }

    public string venda_dav_item_lote_numero { get; set; }

    public Nullable<System.DateTime> venda_dav_item_lote_validade { get; set; }

    public Nullable<System.DateTime> venda_dav_item_lote_fabricacao { get; set; }

    public Nullable<decimal> venda_dav_item_lote_vlr_pmc { get; set; }

    public Nullable<int> venda_dav_item_fpop_qtde_diaria { get; set; }

    public Nullable<int> venda_dav_item_fpop_qtde_unitaria { get; set; }

    public Nullable<int> pro_id { get; set; }

    public Nullable<int> crm_id { get; set; }

    public Nullable<int> treceita_id { get; set; }



    public virtual tb_produto tb_produto { get; set; }

    public virtual tb_venda_dav tb_venda_dav { get; set; }

    public virtual tb_venda_dav_item tb_venda_dav_item1 { get; set; }

    public virtual tb_venda_dav_item tb_venda_dav_item2 { get; set; }

}

}
