
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tbr_parametro_markup_uneg
{

    public int par_id { get; set; }

    public int uneg_id { get; set; }

    public Nullable<decimal> par_percentual { get; set; }



    public virtual tb_parametro_markup tb_parametro_markup { get; set; }

    public virtual tb_unid_negocio tb_unid_negocio { get; set; }

}

}
