
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tbr_promocao_produto
{

    public int prm_id { get; set; }

    public int pro_id { get; set; }

    public Nullable<decimal> prom_preco { get; set; }

    public string prom_situacao { get; set; }

    public Nullable<System.DateTime> prom_dt_cadastro { get; set; }

    public Nullable<System.DateTime> prom_dt_alteracao { get; set; }

    public Nullable<decimal> prom_cpf_alteracao { get; set; }

    public string prom_app_alteracao { get; set; }



    public virtual tb_promocao tb_promocao { get; set; }

}

}
