
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tbr_convenio_finalizadora_sub
{

    public int cnv_id { get; set; }

    public int final_id { get; set; }

    public int subfin_id { get; set; }

    public string cfinaliza_situacao { get; set; }

    public Nullable<System.DateTime> cfinaliza_dt_cadastro { get; set; }

    public Nullable<System.DateTime> cfinaliza_dt_alteracao { get; set; }

    public Nullable<decimal> cfinaliza_cpf_alteracao { get; set; }



    public virtual tb_convenio tb_convenio { get; set; }

}

}
