
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tbr_produto_uneg
{

    public int uneg_id { get; set; }

    public int pro_id { get; set; }

    public Nullable<decimal> proun_preco_venda { get; set; }

    public string proun_situacao { get; set; }

    public Nullable<decimal> proun_custo_nf { get; set; }

    public Nullable<decimal> proun_encargos_nf { get; set; }

    public Nullable<decimal> proun_descontos_nf { get; set; }

    public Nullable<decimal> proun_custo_real { get; set; }

    public Nullable<decimal> proun_custo_medio { get; set; }

    public Nullable<decimal> proun_dia_min { get; set; }

    public Nullable<decimal> proun_dia_max { get; set; }

    public Nullable<decimal> proun_qtd_min { get; set; }

    public Nullable<decimal> proun_qtd_max { get; set; }

    public Nullable<bool> proun_fixa_qtd_max { get; set; }

    public Nullable<decimal> proun_vnd_media { get; set; }

    public Nullable<bool> proun_repos_auto { get; set; }

    public string proun_abc_qtde { get; set; }

    public string proun_abc_val { get; set; }

    public string proun_abc_mrg { get; set; }

    public Nullable<decimal> proun_abc_qtde_rank { get; set; }

    public Nullable<decimal> proun_abc_val_rank { get; set; }

    public Nullable<decimal> proun_abc_mrg_rank { get; set; }

    public Nullable<decimal> proun_qtd_estoque { get; set; }

    public Nullable<decimal> proun_qtd_pedida { get; set; }

    public Nullable<decimal> proun_qtd_transferida { get; set; }

    public Nullable<System.DateTime> proun_dt_ult_compra { get; set; }

    public Nullable<System.DateTime> proun_dt_ult_venda { get; set; }

    public Nullable<System.DateTime> proun_dt_ult_mvto { get; set; }

    public Nullable<System.DateTime> proun_dt_ult_preco { get; set; }

    public Nullable<System.DateTime> proun_dt_cadastro { get; set; }

    public Nullable<System.DateTime> proun_dt_alteracao { get; set; }

    public Nullable<bool> proun_bloq_compra { get; set; }

    public Nullable<System.DateTime> proun_dt_ult_inventario { get; set; }

    public Nullable<int> proun_id_ult_fornecedor { get; set; }



    public virtual tb_produto tb_produto { get; set; }

    public virtual tb_unid_negocio tb_unid_negocio { get; set; }

}

}
