
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tbr_abcfarma_uf
{

    public int per_id { get; set; }

    public int abcf_id { get; set; }

    public int uf_id { get; set; }

    public Nullable<decimal> prouf_preco_fabrica { get; set; }

    public Nullable<decimal> prouf_pmc { get; set; }

    public Nullable<decimal> prouf_pmc_fracao { get; set; }

    public string prouf_situacao { get; set; }

    public Nullable<System.DateTime> prouf_dt_cadastro { get; set; }

    public Nullable<System.DateTime> prouf_dt_alteracao { get; set; }



    public virtual tb_abcfarma tb_abcfarma { get; set; }

    public virtual tb_abcfarma_periodo tb_abcfarma_periodo { get; set; }

    public virtual tb_uf tb_uf { get; set; }

}

}
