
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tbr_mvto_compra_dup____
{

    public int cmp_id { get; set; }

    public int cmpdup_id { get; set; }

    public string mvtocdup_situacao { get; set; }

    public Nullable<System.DateTime> mvtocdup_dt_cadastro { get; set; }

    public Nullable<System.DateTime> mvtocdup_dt_alteracao { get; set; }

    public Nullable<decimal> mvtocdup_cpf_alteracao { get; set; }



    public virtual tb_mvto_compra____ tb_mvto_compra____ { get; set; }

    public virtual tb_mvto_compra_dup____ tb_mvto_compra_dup____ { get; set; }

}

}
