
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tbr_dpto_aplicativo
{

    public int dpto_id { get; set; }

    public int apl_id { get; set; }

    public Nullable<int> dptapl_acesso { get; set; }

    public Nullable<bool> dptapl_inclusao { get; set; }

    public Nullable<bool> dptapl_alteracao { get; set; }

    public Nullable<bool> dptapl_exclusao { get; set; }

    public Nullable<bool> dptapl_impressao { get; set; }

    public Nullable<bool> dptapl_exp_xls { get; set; }

    public Nullable<bool> dptapl_exp_pdf { get; set; }

    public Nullable<bool> dptapl_exp_txt { get; set; }

    public Nullable<bool> dptapl_processo { get; set; }

    public Nullable<bool> dptapl_edicao { get; set; }

    public Nullable<System.DateTime> dptapl_dt_cadastro { get; set; }

    public Nullable<System.DateTime> dptapl_dt_alteracao { get; set; }

    public string dptapl_aplicacao { get; set; }



    public virtual tb_usuario_dpto tb_usuario_dpto { get; set; }

}

}
