
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tbr_finalizadora_un
{

    public int uneg_id { get; set; }

    public int final_id { get; set; }

    public string finalun_situacao { get; set; }

    public Nullable<System.DateTime> finalun_dt_cadastro { get; set; }

    public Nullable<System.DateTime> finalun_dt_alteracao { get; set; }

    public Nullable<decimal> finalun_cpf_alteracao { get; set; }



    public virtual tb_finalizadora tb_finalizadora { get; set; }

    public virtual tb_unid_negocio tb_unid_negocio { get; set; }

}

}
