
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tbr_finalizadora_sub_un
{

    public int final_id { get; set; }

    public int subfin_id { get; set; }

    public int uneg_id { get; set; }

    public Nullable<decimal> finsubun_taxa_adm { get; set; }

    public string finsubun_situacao { get; set; }

    public Nullable<System.DateTime> finsubun_dt_cadastro { get; set; }

    public Nullable<System.DateTime> finsubun_dt_alteracao { get; set; }

    public Nullable<decimal> finsubun_cpf_alteracao { get; set; }

    public Nullable<int> banco_id { get; set; }



    public virtual tb_finalizadora_sub tb_finalizadora_sub { get; set; }

    public virtual tb_financeiro_bancos tb_financeiro_bancos { get; set; }

    public virtual tb_unid_negocio tb_unid_negocio { get; set; }

}

}
