
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tbr_produto_estoque_lote
{

    public int uneg_id { get; set; }

    public int pro_id { get; set; }

    public string lote_numero { get; set; }

    public System.DateTime lote_validade { get; set; }

    public Nullable<decimal> lote_estoque { get; set; }

    public Nullable<System.DateTime> lote_fabricacao { get; set; }

    public Nullable<decimal> lote_vlr_pmc { get; set; }

    public Nullable<System.DateTime> lote_dt_alteracao { get; set; }



    public virtual tb_produto tb_produto { get; set; }

    public virtual tb_unid_negocio tb_unid_negocio { get; set; }

}

}
