
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tbr_ecf_finalizadora
{

    public int final_id { get; set; }

    public string ecf_numero_serie { get; set; }

    public string finalecf_codigo { get; set; }

    public bool finalecf_cupom_vinculado { get; set; }

    public string finalecf_situacao { get; set; }

    public System.DateTime finalecf_dt_cadastro { get; set; }

    public Nullable<System.DateTime> finalecf_dt_alteracao { get; set; }



    public virtual tb_ecf tb_ecf { get; set; }

    public virtual tb_finalizadora tb_finalizadora { get; set; }

}

}
