
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ASArquiteruraData
{

using System;
    using System.Collections.Generic;
    
public partial class tbr_mvto_compra_cfop____
{

    public int cmp_id { get; set; }

    public int cfop_id { get; set; }

    public Nullable<decimal> mvtoccfop_base_icms { get; set; }

    public Nullable<decimal> mvtoccfop_aliq_icms { get; set; }

    public Nullable<decimal> mvtoccfop_valor_icms { get; set; }

    public string mvtoccfop_situacao { get; set; }

    public Nullable<System.DateTime> mvtoccfop_dt_cadastro { get; set; }

    public Nullable<System.DateTime> mvtoccfop_dt_alteracao { get; set; }

    public Nullable<decimal> mvtoccfop_cpf_alteracao { get; set; }



    public virtual tb_cfop tb_cfop { get; set; }

    public virtual tb_mvto_compra____ tb_mvto_compra____ { get; set; }

}

}
